/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddScopeRequest,
  CreateAPIKeyRequest,
  CreateAPIKeyResponse,
  ErrorResponse,
  GetAPIKeyResponse,
  ListAPIKeysResponse,
  ListScopesResponse,
  MessageResponse2
} from '.././models';

import { apiClient } from '../../../lib/api';




/**
 * Returns all API keys belonging to the authenticated user.
 * @summary List API keys
 */
export const getApiV1ApiKeys = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<ListAPIKeysResponse>(
      {url: `/api/v1/api-keys`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1ApiKeysQueryKey = () => {
    return [
    `/api/v1/api-keys`
    ] as const;
    }

    
export const getGetApiV1ApiKeysQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ApiKeys>>, TError = ErrorResponse | void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ApiKeys>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ApiKeysQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ApiKeys>>> = ({ signal }) => getApiV1ApiKeys(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ApiKeys>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ApiKeysQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ApiKeys>>>
export type GetApiV1ApiKeysQueryError = ErrorResponse | void


export function useGetApiV1ApiKeys<TData = Awaited<ReturnType<typeof getApiV1ApiKeys>>, TError = ErrorResponse | void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ApiKeys>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ApiKeys>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ApiKeys>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ApiKeys<TData = Awaited<ReturnType<typeof getApiV1ApiKeys>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ApiKeys>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ApiKeys>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ApiKeys>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ApiKeys<TData = Awaited<ReturnType<typeof getApiV1ApiKeys>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ApiKeys>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List API keys
 */

export function useGetApiV1ApiKeys<TData = Awaited<ReturnType<typeof getApiV1ApiKeys>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ApiKeys>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ApiKeysQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Creates a new API key for the authenticated user. The plain key is only returned once at creation time.
 * @summary Create API key
 */
export const postApiV1ApiKeys = (
    createAPIKeyRequest: CreateAPIKeyRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<CreateAPIKeyResponse>(
      {url: `/api/v1/api-keys`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createAPIKeyRequest, signal
    },
      );
    }
  


export const getPostApiV1ApiKeysMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ApiKeys>>, TError,{data: CreateAPIKeyRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1ApiKeys>>, TError,{data: CreateAPIKeyRequest}, TContext> => {

const mutationKey = ['postApiV1ApiKeys'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1ApiKeys>>, {data: CreateAPIKeyRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1ApiKeys(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1ApiKeysMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1ApiKeys>>>
    export type PostApiV1ApiKeysMutationBody = CreateAPIKeyRequest
    export type PostApiV1ApiKeysMutationError = ErrorResponse | void

    /**
 * @summary Create API key
 */
export const usePostApiV1ApiKeys = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ApiKeys>>, TError,{data: CreateAPIKeyRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1ApiKeys>>,
        TError,
        {data: CreateAPIKeyRequest},
        TContext
      > => {
      return useMutation(getPostApiV1ApiKeysMutationOptions(options), queryClient);
    }
    /**
 * Revokes (deletes) an API key. This action cannot be undone.
 * @summary Revoke API key
 */
export const deleteApiV1ApiKeysId = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return apiClient<MessageResponse2>(
      {url: `/api/v1/api-keys/${id}`, method: 'DELETE', signal
    },
      );
    }
  


export const getDeleteApiV1ApiKeysIdMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1ApiKeysId>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1ApiKeysId>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteApiV1ApiKeysId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1ApiKeysId>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV1ApiKeysId(id,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1ApiKeysIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1ApiKeysId>>>
    
    export type DeleteApiV1ApiKeysIdMutationError = ErrorResponse | void

    /**
 * @summary Revoke API key
 */
export const useDeleteApiV1ApiKeysId = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1ApiKeysId>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1ApiKeysId>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteApiV1ApiKeysIdMutationOptions(options), queryClient);
    }
    /**
 * Returns details of a specific API key.
 * @summary Get API key
 */
export const getApiV1ApiKeysId = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return apiClient<GetAPIKeyResponse>(
      {url: `/api/v1/api-keys/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1ApiKeysIdQueryKey = (id?: number,) => {
    return [
    `/api/v1/api-keys/${id}`
    ] as const;
    }

    
export const getGetApiV1ApiKeysIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ApiKeysId>>, TError = ErrorResponse | void>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ApiKeysId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ApiKeysIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ApiKeysId>>> = ({ signal }) => getApiV1ApiKeysId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ApiKeysId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ApiKeysIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ApiKeysId>>>
export type GetApiV1ApiKeysIdQueryError = ErrorResponse | void


export function useGetApiV1ApiKeysId<TData = Awaited<ReturnType<typeof getApiV1ApiKeysId>>, TError = ErrorResponse | void>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ApiKeysId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ApiKeysId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ApiKeysId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ApiKeysId<TData = Awaited<ReturnType<typeof getApiV1ApiKeysId>>, TError = ErrorResponse | void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ApiKeysId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ApiKeysId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ApiKeysId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ApiKeysId<TData = Awaited<ReturnType<typeof getApiV1ApiKeysId>>, TError = ErrorResponse | void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ApiKeysId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get API key
 */

export function useGetApiV1ApiKeysId<TData = Awaited<ReturnType<typeof getApiV1ApiKeysId>>, TError = ErrorResponse | void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ApiKeysId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ApiKeysIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Returns all scopes configured for a specific API key.
 * @summary List API key scopes
 */
export const getApiV1ApiKeysIdScopes = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ListScopesResponse>(
      {url: `/api/v1/api-keys/${id}/scopes`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1ApiKeysIdScopesQueryKey = (id?: number,) => {
    return [
    `/api/v1/api-keys/${id}/scopes`
    ] as const;
    }

    
export const getGetApiV1ApiKeysIdScopesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ApiKeysIdScopes>>, TError = ErrorResponse | void>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ApiKeysIdScopes>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ApiKeysIdScopesQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ApiKeysIdScopes>>> = ({ signal }) => getApiV1ApiKeysIdScopes(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ApiKeysIdScopes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ApiKeysIdScopesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ApiKeysIdScopes>>>
export type GetApiV1ApiKeysIdScopesQueryError = ErrorResponse | void


export function useGetApiV1ApiKeysIdScopes<TData = Awaited<ReturnType<typeof getApiV1ApiKeysIdScopes>>, TError = ErrorResponse | void>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ApiKeysIdScopes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ApiKeysIdScopes>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ApiKeysIdScopes>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ApiKeysIdScopes<TData = Awaited<ReturnType<typeof getApiV1ApiKeysIdScopes>>, TError = ErrorResponse | void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ApiKeysIdScopes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ApiKeysIdScopes>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ApiKeysIdScopes>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ApiKeysIdScopes<TData = Awaited<ReturnType<typeof getApiV1ApiKeysIdScopes>>, TError = ErrorResponse | void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ApiKeysIdScopes>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List API key scopes
 */

export function useGetApiV1ApiKeysIdScopes<TData = Awaited<ReturnType<typeof getApiV1ApiKeysIdScopes>>, TError = ErrorResponse | void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ApiKeysIdScopes>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ApiKeysIdScopesQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Adds a new permission scope to an API key. The scope limits what the API key can access.
 * @summary Add scope to API key
 */
export const postApiV1ApiKeysIdScopes = (
    id: number,
    addScopeRequest: AddScopeRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<MessageResponse2>(
      {url: `/api/v1/api-keys/${id}/scopes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addScopeRequest, signal
    },
      );
    }
  


export const getPostApiV1ApiKeysIdScopesMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ApiKeysIdScopes>>, TError,{id: number;data: AddScopeRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1ApiKeysIdScopes>>, TError,{id: number;data: AddScopeRequest}, TContext> => {

const mutationKey = ['postApiV1ApiKeysIdScopes'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1ApiKeysIdScopes>>, {id: number;data: AddScopeRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiV1ApiKeysIdScopes(id,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1ApiKeysIdScopesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1ApiKeysIdScopes>>>
    export type PostApiV1ApiKeysIdScopesMutationBody = AddScopeRequest
    export type PostApiV1ApiKeysIdScopesMutationError = ErrorResponse | void

    /**
 * @summary Add scope to API key
 */
export const usePostApiV1ApiKeysIdScopes = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ApiKeysIdScopes>>, TError,{id: number;data: AddScopeRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1ApiKeysIdScopes>>,
        TError,
        {id: number;data: AddScopeRequest},
        TContext
      > => {
      return useMutation(getPostApiV1ApiKeysIdScopesMutationOptions(options), queryClient);
    }
    /**
 * Removes a permission scope from an API key.
 * @summary Remove scope from API key
 */
export const deleteApiV1ApiKeysIdScopesScopeId = (
    id: number,
    scopeId: number,
 signal?: AbortSignal
) => {
      
      
      return apiClient<MessageResponse2>(
      {url: `/api/v1/api-keys/${id}/scopes/${scopeId}`, method: 'DELETE', signal
    },
      );
    }
  


export const getDeleteApiV1ApiKeysIdScopesScopeIdMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1ApiKeysIdScopesScopeId>>, TError,{id: number;scopeId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1ApiKeysIdScopesScopeId>>, TError,{id: number;scopeId: number}, TContext> => {

const mutationKey = ['deleteApiV1ApiKeysIdScopesScopeId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1ApiKeysIdScopesScopeId>>, {id: number;scopeId: number}> = (props) => {
          const {id,scopeId} = props ?? {};

          return  deleteApiV1ApiKeysIdScopesScopeId(id,scopeId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1ApiKeysIdScopesScopeIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1ApiKeysIdScopesScopeId>>>
    
    export type DeleteApiV1ApiKeysIdScopesScopeIdMutationError = ErrorResponse | void

    /**
 * @summary Remove scope from API key
 */
export const useDeleteApiV1ApiKeysIdScopesScopeId = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1ApiKeysIdScopesScopeId>>, TError,{id: number;scopeId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1ApiKeysIdScopesScopeId>>,
        TError,
        {id: number;scopeId: number},
        TContext
      > => {
      return useMutation(getDeleteApiV1ApiKeysIdScopesScopeIdMutationOptions(options), queryClient);
    }
    