/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateCredentialRequest,
  CreateCredentialResponse,
  DeleteCredentialResponse,
  ErrorResponse,
  GetCredentialResponse,
  ListCredentialsResponse,
  UpdateCredentialRequest,
  UpdateCredentialResponse
} from '.././models';

import { apiClient } from '../../../lib/api';




/**
 * Returns all registry credentials for a server. Requires registries.manage permission.
 * @summary List registry credentials
 */
export const getApiV1ServersServeridRegistries = (
    serverid: number,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ListCredentialsResponse>(
      {url: `/api/v1/servers/${serverid}/registries`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1ServersServeridRegistriesQueryKey = (serverid?: number,) => {
    return [
    `/api/v1/servers/${serverid}/registries`
    ] as const;
    }

    
export const getGetApiV1ServersServeridRegistriesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ServersServeridRegistries>>, TError = ErrorResponse | void>(serverid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridRegistries>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ServersServeridRegistriesQueryKey(serverid);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ServersServeridRegistries>>> = ({ signal }) => getApiV1ServersServeridRegistries(serverid, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(serverid), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridRegistries>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ServersServeridRegistriesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ServersServeridRegistries>>>
export type GetApiV1ServersServeridRegistriesQueryError = ErrorResponse | void


export function useGetApiV1ServersServeridRegistries<TData = Awaited<ReturnType<typeof getApiV1ServersServeridRegistries>>, TError = ErrorResponse | void>(
 serverid: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridRegistries>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ServersServeridRegistries>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ServersServeridRegistries>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ServersServeridRegistries<TData = Awaited<ReturnType<typeof getApiV1ServersServeridRegistries>>, TError = ErrorResponse | void>(
 serverid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridRegistries>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ServersServeridRegistries>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ServersServeridRegistries>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ServersServeridRegistries<TData = Awaited<ReturnType<typeof getApiV1ServersServeridRegistries>>, TError = ErrorResponse | void>(
 serverid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridRegistries>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List registry credentials
 */

export function useGetApiV1ServersServeridRegistries<TData = Awaited<ReturnType<typeof getApiV1ServersServeridRegistries>>, TError = ErrorResponse | void>(
 serverid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridRegistries>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ServersServeridRegistriesQueryOptions(serverid,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Creates a new registry credential for a server. Requires registries.manage permission.
 * @summary Create registry credential
 */
export const postApiV1ServersServeridRegistries = (
    serverid: number,
    createCredentialRequest: CreateCredentialRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<CreateCredentialResponse>(
      {url: `/api/v1/servers/${serverid}/registries`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCredentialRequest, signal
    },
      );
    }
  


export const getPostApiV1ServersServeridRegistriesMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ServersServeridRegistries>>, TError,{serverid: number;data: CreateCredentialRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1ServersServeridRegistries>>, TError,{serverid: number;data: CreateCredentialRequest}, TContext> => {

const mutationKey = ['postApiV1ServersServeridRegistries'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1ServersServeridRegistries>>, {serverid: number;data: CreateCredentialRequest}> = (props) => {
          const {serverid,data} = props ?? {};

          return  postApiV1ServersServeridRegistries(serverid,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1ServersServeridRegistriesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1ServersServeridRegistries>>>
    export type PostApiV1ServersServeridRegistriesMutationBody = CreateCredentialRequest
    export type PostApiV1ServersServeridRegistriesMutationError = ErrorResponse | void

    /**
 * @summary Create registry credential
 */
export const usePostApiV1ServersServeridRegistries = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ServersServeridRegistries>>, TError,{serverid: number;data: CreateCredentialRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1ServersServeridRegistries>>,
        TError,
        {serverid: number;data: CreateCredentialRequest},
        TContext
      > => {
      return useMutation(getPostApiV1ServersServeridRegistriesMutationOptions(options), queryClient);
    }
    /**
 * Deletes a registry credential. Requires registries.manage permission.
 * @summary Delete registry credential
 */
export const deleteApiV1ServersServeridRegistriesId = (
    serverid: number,
    id: number,
 signal?: AbortSignal
) => {
      
      
      return apiClient<DeleteCredentialResponse>(
      {url: `/api/v1/servers/${serverid}/registries/${id}`, method: 'DELETE', signal
    },
      );
    }
  


export const getDeleteApiV1ServersServeridRegistriesIdMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1ServersServeridRegistriesId>>, TError,{serverid: number;id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1ServersServeridRegistriesId>>, TError,{serverid: number;id: number}, TContext> => {

const mutationKey = ['deleteApiV1ServersServeridRegistriesId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1ServersServeridRegistriesId>>, {serverid: number;id: number}> = (props) => {
          const {serverid,id} = props ?? {};

          return  deleteApiV1ServersServeridRegistriesId(serverid,id,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1ServersServeridRegistriesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1ServersServeridRegistriesId>>>
    
    export type DeleteApiV1ServersServeridRegistriesIdMutationError = ErrorResponse | void

    /**
 * @summary Delete registry credential
 */
export const useDeleteApiV1ServersServeridRegistriesId = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1ServersServeridRegistriesId>>, TError,{serverid: number;id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1ServersServeridRegistriesId>>,
        TError,
        {serverid: number;id: number},
        TContext
      > => {
      return useMutation(getDeleteApiV1ServersServeridRegistriesIdMutationOptions(options), queryClient);
    }
    /**
 * Returns a specific registry credential by ID. Requires registries.manage permission.
 * @summary Get registry credential
 */
export const getApiV1ServersServeridRegistriesId = (
    serverid: number,
    id: number,
 signal?: AbortSignal
) => {
      
      
      return apiClient<GetCredentialResponse>(
      {url: `/api/v1/servers/${serverid}/registries/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1ServersServeridRegistriesIdQueryKey = (serverid?: number,
    id?: number,) => {
    return [
    `/api/v1/servers/${serverid}/registries/${id}`
    ] as const;
    }

    
export const getGetApiV1ServersServeridRegistriesIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ServersServeridRegistriesId>>, TError = ErrorResponse | void>(serverid: number,
    id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridRegistriesId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ServersServeridRegistriesIdQueryKey(serverid,id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ServersServeridRegistriesId>>> = ({ signal }) => getApiV1ServersServeridRegistriesId(serverid,id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(serverid && id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridRegistriesId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ServersServeridRegistriesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ServersServeridRegistriesId>>>
export type GetApiV1ServersServeridRegistriesIdQueryError = ErrorResponse | void


export function useGetApiV1ServersServeridRegistriesId<TData = Awaited<ReturnType<typeof getApiV1ServersServeridRegistriesId>>, TError = ErrorResponse | void>(
 serverid: number,
    id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridRegistriesId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ServersServeridRegistriesId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ServersServeridRegistriesId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ServersServeridRegistriesId<TData = Awaited<ReturnType<typeof getApiV1ServersServeridRegistriesId>>, TError = ErrorResponse | void>(
 serverid: number,
    id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridRegistriesId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ServersServeridRegistriesId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ServersServeridRegistriesId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ServersServeridRegistriesId<TData = Awaited<ReturnType<typeof getApiV1ServersServeridRegistriesId>>, TError = ErrorResponse | void>(
 serverid: number,
    id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridRegistriesId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get registry credential
 */

export function useGetApiV1ServersServeridRegistriesId<TData = Awaited<ReturnType<typeof getApiV1ServersServeridRegistriesId>>, TError = ErrorResponse | void>(
 serverid: number,
    id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridRegistriesId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ServersServeridRegistriesIdQueryOptions(serverid,id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Updates an existing registry credential. Requires registries.manage permission.
 * @summary Update registry credential
 */
export const putApiV1ServersServeridRegistriesId = (
    serverid: number,
    id: number,
    updateCredentialRequest: UpdateCredentialRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<UpdateCredentialResponse>(
      {url: `/api/v1/servers/${serverid}/registries/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateCredentialRequest, signal
    },
      );
    }
  


export const getPutApiV1ServersServeridRegistriesIdMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1ServersServeridRegistriesId>>, TError,{serverid: number;id: number;data: UpdateCredentialRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiV1ServersServeridRegistriesId>>, TError,{serverid: number;id: number;data: UpdateCredentialRequest}, TContext> => {

const mutationKey = ['putApiV1ServersServeridRegistriesId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1ServersServeridRegistriesId>>, {serverid: number;id: number;data: UpdateCredentialRequest}> = (props) => {
          const {serverid,id,data} = props ?? {};

          return  putApiV1ServersServeridRegistriesId(serverid,id,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV1ServersServeridRegistriesIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1ServersServeridRegistriesId>>>
    export type PutApiV1ServersServeridRegistriesIdMutationBody = UpdateCredentialRequest
    export type PutApiV1ServersServeridRegistriesIdMutationError = ErrorResponse | void

    /**
 * @summary Update registry credential
 */
export const usePutApiV1ServersServeridRegistriesId = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1ServersServeridRegistriesId>>, TError,{serverid: number;id: number;data: UpdateCredentialRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV1ServersServeridRegistriesId>>,
        TError,
        {serverid: number;id: number;data: UpdateCredentialRequest},
        TContext
      > => {
      return useMutation(getPutApiV1ServersServeridRegistriesIdMutationOptions(options), queryClient);
    }
    