/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  GetProfileResponse
} from '.././models';

import { apiClient } from '../../../lib/api';




/**
 * Returns the profile information for the authenticated user including roles and TOTP status.
 * @summary Get current user profile
 */
export const getApiV1Profile = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<GetProfileResponse>(
      {url: `/api/v1/profile`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1ProfileQueryKey = () => {
    return [
    `/api/v1/profile`
    ] as const;
    }

    
export const getGetApiV1ProfileQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1Profile>>, TError = ErrorResponse | void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Profile>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ProfileQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Profile>>> = ({ signal }) => getApiV1Profile(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1Profile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ProfileQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Profile>>>
export type GetApiV1ProfileQueryError = ErrorResponse | void


export function useGetApiV1Profile<TData = Awaited<ReturnType<typeof getApiV1Profile>>, TError = ErrorResponse | void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Profile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Profile>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Profile>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Profile<TData = Awaited<ReturnType<typeof getApiV1Profile>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Profile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Profile>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Profile>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Profile<TData = Awaited<ReturnType<typeof getApiV1Profile>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Profile>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get current user profile
 */

export function useGetApiV1Profile<TData = Awaited<ReturnType<typeof getApiV1Profile>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Profile>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ProfileQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




