/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  AuthErrorResponse,
  AuthLoginRequest,
  AuthLoginResponse,
  AuthLogoutRequest,
  AuthLogoutResponse,
  AuthRefreshRequest,
  AuthRefreshResponse,
  AuthTOTPRequiredResponse,
  AuthTOTPVerifyRequest
} from '.././models';

import { apiClient } from '../../../lib/api';




/**
 * Authenticates a user with username and password. If TOTP is enabled, returns a temporary token that must be used with /auth/totp/verify to complete authentication.
 * @summary Login with username and password
 */
export const postApiV1AuthLogin = (
    authLoginRequest: AuthLoginRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<AuthTOTPRequiredResponse>(
      {url: `/api/v1/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: authLoginRequest, signal
    },
      );
    }
  


export const getPostApiV1AuthLoginMutationOptions = <TError = AuthErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthLogin>>, TError,{data: AuthLoginRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthLogin>>, TError,{data: AuthLoginRequest}, TContext> => {

const mutationKey = ['postApiV1AuthLogin'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AuthLogin>>, {data: AuthLoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AuthLogin(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AuthLogin>>>
    export type PostApiV1AuthLoginMutationBody = AuthLoginRequest
    export type PostApiV1AuthLoginMutationError = AuthErrorResponse | void

    /**
 * @summary Login with username and password
 */
export const usePostApiV1AuthLogin = <TError = AuthErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthLogin>>, TError,{data: AuthLoginRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AuthLogin>>,
        TError,
        {data: AuthLoginRequest},
        TContext
      > => {
      return useMutation(getPostApiV1AuthLoginMutationOptions(options), queryClient);
    }
    /**
 * Revokes the access token and refresh token, effectively logging the user out. The refresh token must be provided in the request body.
 * @summary Logout and revoke tokens
 */
export const postApiV1AuthLogout = (
    authLogoutRequest: AuthLogoutRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<AuthLogoutResponse>(
      {url: `/api/v1/auth/logout`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: authLogoutRequest, signal
    },
      );
    }
  


export const getPostApiV1AuthLogoutMutationOptions = <TError = AuthErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthLogout>>, TError,{data: AuthLogoutRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthLogout>>, TError,{data: AuthLogoutRequest}, TContext> => {

const mutationKey = ['postApiV1AuthLogout'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AuthLogout>>, {data: AuthLogoutRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AuthLogout(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AuthLogout>>>
    export type PostApiV1AuthLogoutMutationBody = AuthLogoutRequest
    export type PostApiV1AuthLogoutMutationError = AuthErrorResponse | void

    /**
 * @summary Logout and revoke tokens
 */
export const usePostApiV1AuthLogout = <TError = AuthErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthLogout>>, TError,{data: AuthLogoutRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AuthLogout>>,
        TError,
        {data: AuthLogoutRequest},
        TContext
      > => {
      return useMutation(getPostApiV1AuthLogoutMutationOptions(options), queryClient);
    }
    /**
 * Exchanges a valid refresh token for new access and refresh tokens. Implements token rotation - the old refresh token is invalidated.
 * @summary Refresh access token
 */
export const postApiV1AuthRefresh = (
    authRefreshRequest: AuthRefreshRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<AuthRefreshResponse>(
      {url: `/api/v1/auth/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: authRefreshRequest, signal
    },
      );
    }
  


export const getPostApiV1AuthRefreshMutationOptions = <TError = AuthErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthRefresh>>, TError,{data: AuthRefreshRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthRefresh>>, TError,{data: AuthRefreshRequest}, TContext> => {

const mutationKey = ['postApiV1AuthRefresh'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AuthRefresh>>, {data: AuthRefreshRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AuthRefresh(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AuthRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AuthRefresh>>>
    export type PostApiV1AuthRefreshMutationBody = AuthRefreshRequest
    export type PostApiV1AuthRefreshMutationError = AuthErrorResponse | void

    /**
 * @summary Refresh access token
 */
export const usePostApiV1AuthRefresh = <TError = AuthErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthRefresh>>, TError,{data: AuthRefreshRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AuthRefresh>>,
        TError,
        {data: AuthRefreshRequest},
        TContext
      > => {
      return useMutation(getPostApiV1AuthRefreshMutationOptions(options), queryClient);
    }
    /**
 * Completes the login flow when TOTP is enabled. Requires the temporary token from /auth/login and a valid TOTP code from the authenticator app.
 * @summary Verify TOTP code to complete login
 */
export const postApiV1AuthTotpVerify = (
    authTOTPVerifyRequest: AuthTOTPVerifyRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<AuthLoginResponse>(
      {url: `/api/v1/auth/totp/verify`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: authTOTPVerifyRequest, signal
    },
      );
    }
  


export const getPostApiV1AuthTotpVerifyMutationOptions = <TError = AuthErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthTotpVerify>>, TError,{data: AuthTOTPVerifyRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthTotpVerify>>, TError,{data: AuthTOTPVerifyRequest}, TContext> => {

const mutationKey = ['postApiV1AuthTotpVerify'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AuthTotpVerify>>, {data: AuthTOTPVerifyRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AuthTotpVerify(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AuthTotpVerifyMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AuthTotpVerify>>>
    export type PostApiV1AuthTotpVerifyMutationBody = AuthTOTPVerifyRequest
    export type PostApiV1AuthTotpVerifyMutationError = AuthErrorResponse | void

    /**
 * @summary Verify TOTP code to complete login
 */
export const usePostApiV1AuthTotpVerify = <TError = AuthErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthTotpVerify>>, TError,{data: AuthTOTPVerifyRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AuthTotpVerify>>,
        TError,
        {data: AuthTOTPVerifyRequest},
        TContext
      > => {
      return useMutation(getPostApiV1AuthTotpVerifyMutationOptions(options), queryClient);
    }
    