/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  AuthErrorResponse,
  ErrorResponse,
  GetSessionsRequest,
  GetSessionsResponse,
  RevokeAllOtherSessionsRequest,
  RevokeSessionRequest,
  SessionMessageResponse
} from '.././models';

import { apiClient } from '../../../lib/api';




/**
 * Returns all active sessions for the authenticated user. The refresh token must be provided to identify the current session.
 * @summary List user sessions
 */
export const postApiV1Sessions = (
    getSessionsRequest: GetSessionsRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<GetSessionsResponse>(
      {url: `/api/v1/sessions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getSessionsRequest, signal
    },
      );
    }
  


export const getPostApiV1SessionsMutationOptions = <TError = AuthErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Sessions>>, TError,{data: GetSessionsRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1Sessions>>, TError,{data: GetSessionsRequest}, TContext> => {

const mutationKey = ['postApiV1Sessions'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1Sessions>>, {data: GetSessionsRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1Sessions(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SessionsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1Sessions>>>
    export type PostApiV1SessionsMutationBody = GetSessionsRequest
    export type PostApiV1SessionsMutationError = AuthErrorResponse | void

    /**
 * @summary List user sessions
 */
export const usePostApiV1Sessions = <TError = AuthErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Sessions>>, TError,{data: GetSessionsRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1Sessions>>,
        TError,
        {data: GetSessionsRequest},
        TContext
      > => {
      return useMutation(getPostApiV1SessionsMutationOptions(options), queryClient);
    }
    /**
 * Revokes a specific session by ID. The user will be logged out from that device.
 * @summary Revoke a session
 */
export const postApiV1SessionsRevoke = (
    revokeSessionRequest: RevokeSessionRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<SessionMessageResponse>(
      {url: `/api/v1/sessions/revoke`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: revokeSessionRequest, signal
    },
      );
    }
  


export const getPostApiV1SessionsRevokeMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SessionsRevoke>>, TError,{data: RevokeSessionRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SessionsRevoke>>, TError,{data: RevokeSessionRequest}, TContext> => {

const mutationKey = ['postApiV1SessionsRevoke'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SessionsRevoke>>, {data: RevokeSessionRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1SessionsRevoke(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SessionsRevokeMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SessionsRevoke>>>
    export type PostApiV1SessionsRevokeMutationBody = RevokeSessionRequest
    export type PostApiV1SessionsRevokeMutationError = ErrorResponse | void

    /**
 * @summary Revoke a session
 */
export const usePostApiV1SessionsRevoke = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SessionsRevoke>>, TError,{data: RevokeSessionRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SessionsRevoke>>,
        TError,
        {data: RevokeSessionRequest},
        TContext
      > => {
      return useMutation(getPostApiV1SessionsRevokeMutationOptions(options), queryClient);
    }
    /**
 * Revokes all sessions except the current one. For JWT authentication, the refresh token must be provided in the request body.
 * @summary Revoke all other sessions
 */
export const postApiV1SessionsRevokeAllOthers = (
    revokeAllOtherSessionsRequest: RevokeAllOtherSessionsRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<SessionMessageResponse>(
      {url: `/api/v1/sessions/revoke-all-others`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: revokeAllOtherSessionsRequest, signal
    },
      );
    }
  


export const getPostApiV1SessionsRevokeAllOthersMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SessionsRevokeAllOthers>>, TError,{data: RevokeAllOtherSessionsRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SessionsRevokeAllOthers>>, TError,{data: RevokeAllOtherSessionsRequest}, TContext> => {

const mutationKey = ['postApiV1SessionsRevokeAllOthers'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SessionsRevokeAllOthers>>, {data: RevokeAllOtherSessionsRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1SessionsRevokeAllOthers(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SessionsRevokeAllOthersMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SessionsRevokeAllOthers>>>
    export type PostApiV1SessionsRevokeAllOthersMutationBody = RevokeAllOtherSessionsRequest
    export type PostApiV1SessionsRevokeAllOthersMutationError = ErrorResponse | void

    /**
 * @summary Revoke all other sessions
 */
export const usePostApiV1SessionsRevokeAllOthers = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SessionsRevokeAllOthers>>, TError,{data: RevokeAllOtherSessionsRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SessionsRevokeAllOthers>>,
        TError,
        {data: RevokeAllOtherSessionsRequest},
        TContext
      > => {
      return useMutation(getPostApiV1SessionsRevokeAllOthersMutationOptions(options), queryClient);
    }
    