/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  OperationRequest,
  ResponseEmpty,
  ResponseOperationStartData
} from '../models';

import { apiClient } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Starts a Docker Compose operation against the specified stack and returns its operation ID.
 * @summary Start a stack operation
 */
export const getPostApiV1ServersServeridStacksStacknameOperationsUrl = (serverid: number,
    stackname: string,) => {




  return `/api/v1/servers/${serverid}/stacks/${stackname}/operations`
}

export const postApiV1ServersServeridStacksStacknameOperations = async (serverid: number,
    stackname: string,
    operationRequest: OperationRequest, options?: RequestInit): Promise<ResponseOperationStartData> => {

  return apiClient<ResponseOperationStartData>(getPostApiV1ServersServeridStacksStacknameOperationsUrl(serverid,stackname),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      operationRequest,)
  }
);}




export const getPostApiV1ServersServeridStacksStacknameOperationsMutationOptions = <TError = ResponseEmpty | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ServersServeridStacksStacknameOperations>>, TError,{serverid: number;stackname: string;data: OperationRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1ServersServeridStacksStacknameOperations>>, TError,{serverid: number;stackname: string;data: OperationRequest}, TContext> => {

const mutationKey = ['postApiV1ServersServeridStacksStacknameOperations'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1ServersServeridStacksStacknameOperations>>, {serverid: number;stackname: string;data: OperationRequest}> = (props) => {
          const {serverid,stackname,data} = props ?? {};

          return  postApiV1ServersServeridStacksStacknameOperations(serverid,stackname,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1ServersServeridStacksStacknameOperationsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1ServersServeridStacksStacknameOperations>>>
    export type PostApiV1ServersServeridStacksStacknameOperationsMutationBody = OperationRequest
    export type PostApiV1ServersServeridStacksStacknameOperationsMutationError = ResponseEmpty | void

    /**
 * @summary Start a stack operation
 */
export const usePostApiV1ServersServeridStacksStacknameOperations = <TError = ResponseEmpty | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ServersServeridStacksStacknameOperations>>, TError,{serverid: number;stackname: string;data: OperationRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1ServersServeridStacksStacknameOperations>>,
        TError,
        {serverid: number;stackname: string;data: OperationRequest},
        TContext
      > => {
      return useMutation(getPostApiV1ServersServeridStacksStacknameOperationsMutationOptions(options), queryClient);
    }
