/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ResponseEmpty,
  ResponseListServersData,
  ResponseServerStatisticsData
} from '../models';

import { apiClient } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns all servers the authenticated user has permission to access
 * @summary List accessible servers
 */
export const getGetApiV1ServersUrl = () => {




  return `/api/v1/servers`
}

export const getApiV1Servers = async ( options?: RequestInit): Promise<ResponseListServersData> => {

  return apiClient<ResponseListServersData>(getGetApiV1ServersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1ServersQueryKey = () => {
    return [
    `/api/v1/servers`
    ] as const;
    }


export const getGetApiV1ServersQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1Servers>>, TError = ResponseEmpty | void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Servers>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ServersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Servers>>> = ({ signal }) => getApiV1Servers({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1Servers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ServersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Servers>>>
export type GetApiV1ServersQueryError = ResponseEmpty | void


export function useGetApiV1Servers<TData = Awaited<ReturnType<typeof getApiV1Servers>>, TError = ResponseEmpty | void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Servers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Servers>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Servers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Servers<TData = Awaited<ReturnType<typeof getApiV1Servers>>, TError = ResponseEmpty | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Servers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Servers>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Servers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Servers<TData = Awaited<ReturnType<typeof getApiV1Servers>>, TError = ResponseEmpty | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Servers>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List accessible servers
 */

export function useGetApiV1Servers<TData = Awaited<ReturnType<typeof getApiV1Servers>>, TError = ResponseEmpty | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Servers>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ServersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Returns stack statistics for a specific server
 * @summary Get server statistics
 */
export const getGetApiV1ServersServeridStatisticsUrl = (serverid: number,) => {




  return `/api/v1/servers/${serverid}/statistics`
}

export const getApiV1ServersServeridStatistics = async (serverid: number, options?: RequestInit): Promise<ResponseServerStatisticsData> => {

  return apiClient<ResponseServerStatisticsData>(getGetApiV1ServersServeridStatisticsUrl(serverid),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1ServersServeridStatisticsQueryKey = (serverid: number,) => {
    return [
    `/api/v1/servers/${serverid}/statistics`
    ] as const;
    }


export const getGetApiV1ServersServeridStatisticsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>, TError = ResponseEmpty | void>(serverid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ServersServeridStatisticsQueryKey(serverid);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>> = ({ signal }) => getApiV1ServersServeridStatistics(serverid, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(serverid), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ServersServeridStatisticsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>>
export type GetApiV1ServersServeridStatisticsQueryError = ResponseEmpty | void


export function useGetApiV1ServersServeridStatistics<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>, TError = ResponseEmpty | void>(
 serverid: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ServersServeridStatistics<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>, TError = ResponseEmpty | void>(
 serverid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ServersServeridStatistics<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>, TError = ResponseEmpty | void>(
 serverid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get server statistics
 */

export function useGetApiV1ServersServeridStatistics<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>, TError = ResponseEmpty | void>(
 serverid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ServersServeridStatisticsQueryOptions(serverid,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




