/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  ListServersResponse,
  ServerStatisticsResponse
} from '.././models';

import { apiClient } from '../../../lib/api';




/**
 * Returns all servers the authenticated user has permission to access
 * @summary List accessible servers
 */
export const getApiV1Servers = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<ListServersResponse>(
      {url: `/api/v1/servers`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1ServersQueryKey = () => {
    return [
    `/api/v1/servers`
    ] as const;
    }

    
export const getGetApiV1ServersQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1Servers>>, TError = ErrorResponse | void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Servers>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ServersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Servers>>> = ({ signal }) => getApiV1Servers(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1Servers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ServersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Servers>>>
export type GetApiV1ServersQueryError = ErrorResponse | void


export function useGetApiV1Servers<TData = Awaited<ReturnType<typeof getApiV1Servers>>, TError = ErrorResponse | void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Servers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Servers>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Servers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Servers<TData = Awaited<ReturnType<typeof getApiV1Servers>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Servers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Servers>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Servers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Servers<TData = Awaited<ReturnType<typeof getApiV1Servers>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Servers>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List accessible servers
 */

export function useGetApiV1Servers<TData = Awaited<ReturnType<typeof getApiV1Servers>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Servers>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ServersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Returns stack statistics for a specific server
 * @summary Get server statistics
 */
export const getApiV1ServersServeridStatistics = (
    serverid: number,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ServerStatisticsResponse>(
      {url: `/api/v1/servers/${serverid}/statistics`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1ServersServeridStatisticsQueryKey = (serverid?: number,) => {
    return [
    `/api/v1/servers/${serverid}/statistics`
    ] as const;
    }

    
export const getGetApiV1ServersServeridStatisticsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>, TError = ErrorResponse | void>(serverid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ServersServeridStatisticsQueryKey(serverid);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>> = ({ signal }) => getApiV1ServersServeridStatistics(serverid, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(serverid), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ServersServeridStatisticsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>>
export type GetApiV1ServersServeridStatisticsQueryError = ErrorResponse | void


export function useGetApiV1ServersServeridStatistics<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>, TError = ErrorResponse | void>(
 serverid: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ServersServeridStatistics<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>, TError = ErrorResponse | void>(
 serverid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ServersServeridStatistics<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>, TError = ErrorResponse | void>(
 serverid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get server statistics
 */

export function useGetApiV1ServersServeridStatistics<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>, TError = ErrorResponse | void>(
 serverid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStatistics>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ServersServeridStatisticsQueryOptions(serverid,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




