/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  GetApiV1ServersServeridStacksStacknameContainersContainerNameLogsParams,
  GetApiV1ServersServeridStacksStacknameLogsParams,
  LogsResponse
} from '../models';

import { apiClient } from '../../../lib/api';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns logs for a specific container in a stack
 * @summary Get container logs
 */
export const getGetApiV1ServersServeridStacksStacknameContainersContainerNameLogsUrl = (serverid: number,
    stackname: string,
    containerName: string,
    params?: GetApiV1ServersServeridStacksStacknameContainersContainerNameLogsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/servers/${serverid}/stacks/${stackname}/containers/${containerName}/logs?${stringifiedParams}` : `/api/v1/servers/${serverid}/stacks/${stackname}/containers/${containerName}/logs`
}

export const getApiV1ServersServeridStacksStacknameContainersContainerNameLogs = async (serverid: number,
    stackname: string,
    containerName: string,
    params?: GetApiV1ServersServeridStacksStacknameContainersContainerNameLogsParams, options?: RequestInit): Promise<LogsResponse> => {

  return apiClient<LogsResponse>(getGetApiV1ServersServeridStacksStacknameContainersContainerNameLogsUrl(serverid,stackname,containerName,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1ServersServeridStacksStacknameContainersContainerNameLogsQueryKey = (serverid: number,
    stackname: string,
    containerName: string,
    params?: GetApiV1ServersServeridStacksStacknameContainersContainerNameLogsParams,) => {
    return [
    `/api/v1/servers/${serverid}/stacks/${stackname}/containers/${containerName}/logs`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1ServersServeridStacksStacknameContainersContainerNameLogsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameContainersContainerNameLogs>>, TError = ErrorResponse | void>(serverid: number,
    stackname: string,
    containerName: string,
    params?: GetApiV1ServersServeridStacksStacknameContainersContainerNameLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameContainersContainerNameLogs>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ServersServeridStacksStacknameContainersContainerNameLogsQueryKey(serverid,stackname,containerName,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameContainersContainerNameLogs>>> = ({ signal }) => getApiV1ServersServeridStacksStacknameContainersContainerNameLogs(serverid,stackname,containerName,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(serverid && stackname && containerName), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameContainersContainerNameLogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ServersServeridStacksStacknameContainersContainerNameLogsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameContainersContainerNameLogs>>>
export type GetApiV1ServersServeridStacksStacknameContainersContainerNameLogsQueryError = ErrorResponse | void


export function useGetApiV1ServersServeridStacksStacknameContainersContainerNameLogs<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameContainersContainerNameLogs>>, TError = ErrorResponse | void>(
 serverid: number,
    stackname: string,
    containerName: string,
    params: undefined |  GetApiV1ServersServeridStacksStacknameContainersContainerNameLogsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameContainersContainerNameLogs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameContainersContainerNameLogs>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameContainersContainerNameLogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ServersServeridStacksStacknameContainersContainerNameLogs<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameContainersContainerNameLogs>>, TError = ErrorResponse | void>(
 serverid: number,
    stackname: string,
    containerName: string,
    params?: GetApiV1ServersServeridStacksStacknameContainersContainerNameLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameContainersContainerNameLogs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameContainersContainerNameLogs>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameContainersContainerNameLogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ServersServeridStacksStacknameContainersContainerNameLogs<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameContainersContainerNameLogs>>, TError = ErrorResponse | void>(
 serverid: number,
    stackname: string,
    containerName: string,
    params?: GetApiV1ServersServeridStacksStacknameContainersContainerNameLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameContainersContainerNameLogs>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get container logs
 */

export function useGetApiV1ServersServeridStacksStacknameContainersContainerNameLogs<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameContainersContainerNameLogs>>, TError = ErrorResponse | void>(
 serverid: number,
    stackname: string,
    containerName: string,
    params?: GetApiV1ServersServeridStacksStacknameContainersContainerNameLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameContainersContainerNameLogs>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ServersServeridStacksStacknameContainersContainerNameLogsQueryOptions(serverid,stackname,containerName,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Returns logs for all containers in a stack
 * @summary Get stack logs
 */
export const getGetApiV1ServersServeridStacksStacknameLogsUrl = (serverid: number,
    stackname: string,
    params?: GetApiV1ServersServeridStacksStacknameLogsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/servers/${serverid}/stacks/${stackname}/logs?${stringifiedParams}` : `/api/v1/servers/${serverid}/stacks/${stackname}/logs`
}

export const getApiV1ServersServeridStacksStacknameLogs = async (serverid: number,
    stackname: string,
    params?: GetApiV1ServersServeridStacksStacknameLogsParams, options?: RequestInit): Promise<LogsResponse> => {

  return apiClient<LogsResponse>(getGetApiV1ServersServeridStacksStacknameLogsUrl(serverid,stackname,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1ServersServeridStacksStacknameLogsQueryKey = (serverid: number,
    stackname: string,
    params?: GetApiV1ServersServeridStacksStacknameLogsParams,) => {
    return [
    `/api/v1/servers/${serverid}/stacks/${stackname}/logs`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1ServersServeridStacksStacknameLogsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameLogs>>, TError = ErrorResponse | void>(serverid: number,
    stackname: string,
    params?: GetApiV1ServersServeridStacksStacknameLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameLogs>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ServersServeridStacksStacknameLogsQueryKey(serverid,stackname,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameLogs>>> = ({ signal }) => getApiV1ServersServeridStacksStacknameLogs(serverid,stackname,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(serverid && stackname), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameLogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ServersServeridStacksStacknameLogsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameLogs>>>
export type GetApiV1ServersServeridStacksStacknameLogsQueryError = ErrorResponse | void


export function useGetApiV1ServersServeridStacksStacknameLogs<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameLogs>>, TError = ErrorResponse | void>(
 serverid: number,
    stackname: string,
    params: undefined |  GetApiV1ServersServeridStacksStacknameLogsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameLogs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameLogs>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameLogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ServersServeridStacksStacknameLogs<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameLogs>>, TError = ErrorResponse | void>(
 serverid: number,
    stackname: string,
    params?: GetApiV1ServersServeridStacksStacknameLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameLogs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameLogs>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameLogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ServersServeridStacksStacknameLogs<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameLogs>>, TError = ErrorResponse | void>(
 serverid: number,
    stackname: string,
    params?: GetApiV1ServersServeridStacksStacknameLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameLogs>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get stack logs
 */

export function useGetApiV1ServersServeridStacksStacknameLogs<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameLogs>>, TError = ErrorResponse | void>(
 serverid: number,
    stackname: string,
    params?: GetApiV1ServersServeridStacksStacknameLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameLogs>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ServersServeridStacksStacknameLogsQueryOptions(serverid,stackname,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




