/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  RawComposeConfig,
  UpdateComposeRequest,
  UpdateComposeResponse
} from '../models';

import { apiClient } from '../../../lib/api';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns the parsed Docker Compose configuration for a stack. Requires files.read permission.
 * @summary Get compose configuration
 */
export const getGetApiV1ServersServeridStacksStacknameComposeUrl = (serverid: number,
    stackname: string,) => {




  return `/api/v1/servers/${serverid}/stacks/${stackname}/compose`
}

export const getApiV1ServersServeridStacksStacknameCompose = async (serverid: number,
    stackname: string, options?: RequestInit): Promise<RawComposeConfig> => {

  return apiClient<RawComposeConfig>(getGetApiV1ServersServeridStacksStacknameComposeUrl(serverid,stackname),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1ServersServeridStacksStacknameComposeQueryKey = (serverid: number,
    stackname: string,) => {
    return [
    `/api/v1/servers/${serverid}/stacks/${stackname}/compose`
    ] as const;
    }


export const getGetApiV1ServersServeridStacksStacknameComposeQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>, TError = ErrorResponse | void>(serverid: number,
    stackname: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ServersServeridStacksStacknameComposeQueryKey(serverid,stackname);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>> = ({ signal }) => getApiV1ServersServeridStacksStacknameCompose(serverid,stackname, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(serverid && stackname), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ServersServeridStacksStacknameComposeQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>>
export type GetApiV1ServersServeridStacksStacknameComposeQueryError = ErrorResponse | void


export function useGetApiV1ServersServeridStacksStacknameCompose<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>, TError = ErrorResponse | void>(
 serverid: number,
    stackname: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ServersServeridStacksStacknameCompose<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>, TError = ErrorResponse | void>(
 serverid: number,
    stackname: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ServersServeridStacksStacknameCompose<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>, TError = ErrorResponse | void>(
 serverid: number,
    stackname: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get compose configuration
 */

export function useGetApiV1ServersServeridStacksStacknameCompose<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>, TError = ErrorResponse | void>(
 serverid: number,
    stackname: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ServersServeridStacksStacknameComposeQueryOptions(serverid,stackname,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Updates the Docker Compose configuration with the specified changes. Supports preview mode to see changes without applying. Requires files.write permission.
 * @summary Update compose configuration
 */
export const getPatchApiV1ServersServeridStacksStacknameComposeUrl = (serverid: number,
    stackname: string,) => {




  return `/api/v1/servers/${serverid}/stacks/${stackname}/compose`
}

export const patchApiV1ServersServeridStacksStacknameCompose = async (serverid: number,
    stackname: string,
    updateComposeRequest: UpdateComposeRequest, options?: RequestInit): Promise<UpdateComposeResponse> => {

  return apiClient<UpdateComposeResponse>(getPatchApiV1ServersServeridStacksStacknameComposeUrl(serverid,stackname),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateComposeRequest,)
  }
);}




export const getPatchApiV1ServersServeridStacksStacknameComposeMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1ServersServeridStacksStacknameCompose>>, TError,{serverid: number;stackname: string;data: UpdateComposeRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1ServersServeridStacksStacknameCompose>>, TError,{serverid: number;stackname: string;data: UpdateComposeRequest}, TContext> => {

const mutationKey = ['patchApiV1ServersServeridStacksStacknameCompose'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1ServersServeridStacksStacknameCompose>>, {serverid: number;stackname: string;data: UpdateComposeRequest}> = (props) => {
          const {serverid,stackname,data} = props ?? {};

          return  patchApiV1ServersServeridStacksStacknameCompose(serverid,stackname,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1ServersServeridStacksStacknameComposeMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1ServersServeridStacksStacknameCompose>>>
    export type PatchApiV1ServersServeridStacksStacknameComposeMutationBody = UpdateComposeRequest
    export type PatchApiV1ServersServeridStacksStacknameComposeMutationError = ErrorResponse | void

    /**
 * @summary Update compose configuration
 */
export const usePatchApiV1ServersServeridStacksStacknameCompose = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1ServersServeridStacksStacknameCompose>>, TError,{serverid: number;stackname: string;data: UpdateComposeRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1ServersServeridStacksStacknameCompose>>,
        TError,
        {serverid: number;stackname: string;data: UpdateComposeRequest},
        TContext
      > => {
      return useMutation(getPatchApiV1ServersServeridStacksStacknameComposeMutationOptions(options), queryClient);
    }
