/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  RawComposeConfig,
  UpdateComposeRequest,
  UpdateComposeResponse
} from '.././models';

import { apiClient } from '../../../lib/api';




/**
 * Returns the parsed Docker Compose configuration for a stack. Requires files.read permission.
 * @summary Get compose configuration
 */
export const getApiV1ServersServeridStacksStacknameCompose = (
    serverid: number,
    stackname: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<RawComposeConfig>(
      {url: `/api/v1/servers/${serverid}/stacks/${stackname}/compose`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1ServersServeridStacksStacknameComposeQueryKey = (serverid?: number,
    stackname?: string,) => {
    return [
    `/api/v1/servers/${serverid}/stacks/${stackname}/compose`
    ] as const;
    }

    
export const getGetApiV1ServersServeridStacksStacknameComposeQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>, TError = ErrorResponse | void>(serverid: number,
    stackname: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ServersServeridStacksStacknameComposeQueryKey(serverid,stackname);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>> = ({ signal }) => getApiV1ServersServeridStacksStacknameCompose(serverid,stackname, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(serverid && stackname), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ServersServeridStacksStacknameComposeQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>>
export type GetApiV1ServersServeridStacksStacknameComposeQueryError = ErrorResponse | void


export function useGetApiV1ServersServeridStacksStacknameCompose<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>, TError = ErrorResponse | void>(
 serverid: number,
    stackname: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ServersServeridStacksStacknameCompose<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>, TError = ErrorResponse | void>(
 serverid: number,
    stackname: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ServersServeridStacksStacknameCompose<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>, TError = ErrorResponse | void>(
 serverid: number,
    stackname: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get compose configuration
 */

export function useGetApiV1ServersServeridStacksStacknameCompose<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>, TError = ErrorResponse | void>(
 serverid: number,
    stackname: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameCompose>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ServersServeridStacksStacknameComposeQueryOptions(serverid,stackname,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Updates the Docker Compose configuration with the specified changes. Supports preview mode to see changes without applying. Requires files.write permission.
 * @summary Update compose configuration
 */
export const patchApiV1ServersServeridStacksStacknameCompose = (
    serverid: number,
    stackname: string,
    updateComposeRequest: UpdateComposeRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<UpdateComposeResponse>(
      {url: `/api/v1/servers/${serverid}/stacks/${stackname}/compose`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateComposeRequest, signal
    },
      );
    }
  


export const getPatchApiV1ServersServeridStacksStacknameComposeMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1ServersServeridStacksStacknameCompose>>, TError,{serverid: number;stackname: string;data: UpdateComposeRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1ServersServeridStacksStacknameCompose>>, TError,{serverid: number;stackname: string;data: UpdateComposeRequest}, TContext> => {

const mutationKey = ['patchApiV1ServersServeridStacksStacknameCompose'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1ServersServeridStacksStacknameCompose>>, {serverid: number;stackname: string;data: UpdateComposeRequest}> = (props) => {
          const {serverid,stackname,data} = props ?? {};

          return  patchApiV1ServersServeridStacksStacknameCompose(serverid,stackname,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1ServersServeridStacksStacknameComposeMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1ServersServeridStacksStacknameCompose>>>
    export type PatchApiV1ServersServeridStacksStacknameComposeMutationBody = UpdateComposeRequest
    export type PatchApiV1ServersServeridStacksStacknameComposeMutationError = ErrorResponse | void

    /**
 * @summary Update compose configuration
 */
export const usePatchApiV1ServersServeridStacksStacknameCompose = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1ServersServeridStacksStacknameCompose>>, TError,{serverid: number;stackname: string;data: UpdateComposeRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1ServersServeridStacksStacknameCompose>>,
        TError,
        {serverid: number;stackname: string;data: UpdateComposeRequest},
        TContext
      > => {
      return useMutation(getPatchApiV1ServersServeridStacksStacknameComposeMutationOptions(options), queryClient);
    }
    