/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetVersionResponse
} from '.././models';

import { apiClient } from '../../../lib/api';




/**
 * Returns the current version of the Berth application.
 * @summary Get application version
 */
export const getApiV1Version = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<GetVersionResponse>(
      {url: `/api/v1/version`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1VersionQueryKey = () => {
    return [
    `/api/v1/version`
    ] as const;
    }

    
export const getGetApiV1VersionQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1Version>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Version>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1VersionQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Version>>> = ({ signal }) => getApiV1Version(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1Version>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1VersionQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Version>>>
export type GetApiV1VersionQueryError = void


export function useGetApiV1Version<TData = Awaited<ReturnType<typeof getApiV1Version>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Version>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Version>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Version>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Version<TData = Awaited<ReturnType<typeof getApiV1Version>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Version>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Version>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Version>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Version<TData = Awaited<ReturnType<typeof getApiV1Version>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Version>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get application version
 */

export function useGetApiV1Version<TData = Awaited<ReturnType<typeof getApiV1Version>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Version>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1VersionQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




