/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteRequest,
  DeleteResult,
  ErrorResponse,
  MaintenanceInfo,
  PermissionsResponse,
  PruneRequest,
  PruneResult
} from '../models';

import { apiClient } from '../../../lib/api';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns detailed Docker system information including disk usage, images, containers, volumes, networks, and build cache
 * @summary Get Docker system information
 */
export const getGetApiV1ServersServeridMaintenanceInfoUrl = (serverid: number,) => {




  return `/api/v1/servers/${serverid}/maintenance/info`
}

export const getApiV1ServersServeridMaintenanceInfo = async (serverid: number, options?: RequestInit): Promise<MaintenanceInfo> => {

  return apiClient<MaintenanceInfo>(getGetApiV1ServersServeridMaintenanceInfoUrl(serverid),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1ServersServeridMaintenanceInfoQueryKey = (serverid: number,) => {
    return [
    `/api/v1/servers/${serverid}/maintenance/info`
    ] as const;
    }


export const getGetApiV1ServersServeridMaintenanceInfoQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ServersServeridMaintenanceInfo>>, TError = ErrorResponse | void>(serverid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridMaintenanceInfo>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ServersServeridMaintenanceInfoQueryKey(serverid);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ServersServeridMaintenanceInfo>>> = ({ signal }) => getApiV1ServersServeridMaintenanceInfo(serverid, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(serverid), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridMaintenanceInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ServersServeridMaintenanceInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ServersServeridMaintenanceInfo>>>
export type GetApiV1ServersServeridMaintenanceInfoQueryError = ErrorResponse | void


export function useGetApiV1ServersServeridMaintenanceInfo<TData = Awaited<ReturnType<typeof getApiV1ServersServeridMaintenanceInfo>>, TError = ErrorResponse | void>(
 serverid: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridMaintenanceInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ServersServeridMaintenanceInfo>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ServersServeridMaintenanceInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ServersServeridMaintenanceInfo<TData = Awaited<ReturnType<typeof getApiV1ServersServeridMaintenanceInfo>>, TError = ErrorResponse | void>(
 serverid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridMaintenanceInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ServersServeridMaintenanceInfo>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ServersServeridMaintenanceInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ServersServeridMaintenanceInfo<TData = Awaited<ReturnType<typeof getApiV1ServersServeridMaintenanceInfo>>, TError = ErrorResponse | void>(
 serverid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridMaintenanceInfo>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Docker system information
 */

export function useGetApiV1ServersServeridMaintenanceInfo<TData = Awaited<ReturnType<typeof getApiV1ServersServeridMaintenanceInfo>>, TError = ErrorResponse | void>(
 serverid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridMaintenanceInfo>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ServersServeridMaintenanceInfoQueryOptions(serverid,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Returns the user's read and write permissions for Docker maintenance operations on the server
 * @summary Check maintenance permissions
 */
export const getGetApiV1ServersServeridMaintenancePermissionsUrl = (serverid: number,) => {




  return `/api/v1/servers/${serverid}/maintenance/permissions`
}

export const getApiV1ServersServeridMaintenancePermissions = async (serverid: number, options?: RequestInit): Promise<PermissionsResponse> => {

  return apiClient<PermissionsResponse>(getGetApiV1ServersServeridMaintenancePermissionsUrl(serverid),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1ServersServeridMaintenancePermissionsQueryKey = (serverid: number,) => {
    return [
    `/api/v1/servers/${serverid}/maintenance/permissions`
    ] as const;
    }


export const getGetApiV1ServersServeridMaintenancePermissionsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ServersServeridMaintenancePermissions>>, TError = ErrorResponse | void>(serverid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridMaintenancePermissions>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ServersServeridMaintenancePermissionsQueryKey(serverid);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ServersServeridMaintenancePermissions>>> = ({ signal }) => getApiV1ServersServeridMaintenancePermissions(serverid, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(serverid), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridMaintenancePermissions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ServersServeridMaintenancePermissionsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ServersServeridMaintenancePermissions>>>
export type GetApiV1ServersServeridMaintenancePermissionsQueryError = ErrorResponse | void


export function useGetApiV1ServersServeridMaintenancePermissions<TData = Awaited<ReturnType<typeof getApiV1ServersServeridMaintenancePermissions>>, TError = ErrorResponse | void>(
 serverid: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridMaintenancePermissions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ServersServeridMaintenancePermissions>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ServersServeridMaintenancePermissions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ServersServeridMaintenancePermissions<TData = Awaited<ReturnType<typeof getApiV1ServersServeridMaintenancePermissions>>, TError = ErrorResponse | void>(
 serverid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridMaintenancePermissions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ServersServeridMaintenancePermissions>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ServersServeridMaintenancePermissions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ServersServeridMaintenancePermissions<TData = Awaited<ReturnType<typeof getApiV1ServersServeridMaintenancePermissions>>, TError = ErrorResponse | void>(
 serverid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridMaintenancePermissions>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Check maintenance permissions
 */

export function useGetApiV1ServersServeridMaintenancePermissions<TData = Awaited<ReturnType<typeof getApiV1ServersServeridMaintenancePermissions>>, TError = ErrorResponse | void>(
 serverid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridMaintenancePermissions>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ServersServeridMaintenancePermissionsQueryOptions(serverid,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Removes unused Docker resources such as images, containers, volumes, networks, or build cache
 * @summary Prune Docker resources
 */
export const getPostApiV1ServersServeridMaintenancePruneUrl = (serverid: number,) => {




  return `/api/v1/servers/${serverid}/maintenance/prune`
}

export const postApiV1ServersServeridMaintenancePrune = async (serverid: number,
    pruneRequest: PruneRequest, options?: RequestInit): Promise<PruneResult> => {

  return apiClient<PruneResult>(getPostApiV1ServersServeridMaintenancePruneUrl(serverid),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      pruneRequest,)
  }
);}




export const getPostApiV1ServersServeridMaintenancePruneMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ServersServeridMaintenancePrune>>, TError,{serverid: number;data: PruneRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1ServersServeridMaintenancePrune>>, TError,{serverid: number;data: PruneRequest}, TContext> => {

const mutationKey = ['postApiV1ServersServeridMaintenancePrune'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1ServersServeridMaintenancePrune>>, {serverid: number;data: PruneRequest}> = (props) => {
          const {serverid,data} = props ?? {};

          return  postApiV1ServersServeridMaintenancePrune(serverid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1ServersServeridMaintenancePruneMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1ServersServeridMaintenancePrune>>>
    export type PostApiV1ServersServeridMaintenancePruneMutationBody = PruneRequest
    export type PostApiV1ServersServeridMaintenancePruneMutationError = ErrorResponse | void

    /**
 * @summary Prune Docker resources
 */
export const usePostApiV1ServersServeridMaintenancePrune = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ServersServeridMaintenancePrune>>, TError,{serverid: number;data: PruneRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1ServersServeridMaintenancePrune>>,
        TError,
        {serverid: number;data: PruneRequest},
        TContext
      > => {
      return useMutation(getPostApiV1ServersServeridMaintenancePruneMutationOptions(options), queryClient);
    }
    /**
 * Deletes a specific Docker resource (image, container, volume, or network) by ID
 * @summary Delete Docker resource
 */
export const getDeleteApiV1ServersServeridMaintenanceResourceUrl = (serverid: number,) => {




  return `/api/v1/servers/${serverid}/maintenance/resource`
}

export const deleteApiV1ServersServeridMaintenanceResource = async (serverid: number,
    deleteRequest: DeleteRequest, options?: RequestInit): Promise<DeleteResult> => {

  return apiClient<DeleteResult>(getDeleteApiV1ServersServeridMaintenanceResourceUrl(serverid),
  {
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      deleteRequest,)
  }
);}




export const getDeleteApiV1ServersServeridMaintenanceResourceMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1ServersServeridMaintenanceResource>>, TError,{serverid: number;data: DeleteRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1ServersServeridMaintenanceResource>>, TError,{serverid: number;data: DeleteRequest}, TContext> => {

const mutationKey = ['deleteApiV1ServersServeridMaintenanceResource'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1ServersServeridMaintenanceResource>>, {serverid: number;data: DeleteRequest}> = (props) => {
          const {serverid,data} = props ?? {};

          return  deleteApiV1ServersServeridMaintenanceResource(serverid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1ServersServeridMaintenanceResourceMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1ServersServeridMaintenanceResource>>>
    export type DeleteApiV1ServersServeridMaintenanceResourceMutationBody = DeleteRequest
    export type DeleteApiV1ServersServeridMaintenanceResourceMutationError = ErrorResponse | void

    /**
 * @summary Delete Docker resource
 */
export const useDeleteApiV1ServersServeridMaintenanceResource = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1ServersServeridMaintenanceResource>>, TError,{serverid: number;data: DeleteRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1ServersServeridMaintenanceResource>>,
        TError,
        {serverid: number;data: DeleteRequest},
        TContext
      > => {
      return useMutation(getDeleteApiV1ServersServeridMaintenanceResourceMutationOptions(options), queryClient);
    }
