/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminCreateServerResponse,
  AdminDeleteServerResponse,
  AdminListServersResponse,
  AdminTestConnectionResponse,
  AdminUpdateServerResponse,
  AssignRoleRequest,
  AssignRoleResponse,
  CreateRoleRequest,
  CreateRoleResponse,
  CreateStackPermissionRequest,
  CreateStackPermissionResponse,
  CreateUserRequest,
  CreateUserResponse,
  DeleteRoleResponse,
  DeleteStackPermissionResponse,
  ErrorResponse,
  ExportRequest,
  GetApiV1AdminOperationLogsParams,
  GetApiV1AdminPermissionsParams,
  GetApiV1AdminSecurityAuditLogsParams,
  GetLogAPIResponse,
  GetStatsAPIResponse,
  GetUserRolesResponse,
  ImportResponse,
  ListLogsAPIResponse,
  ListPermissionsResponse,
  ListRoleStackPermissionsResponse,
  ListRolesResponse,
  ListUsersResponse,
  OperationLogDetailResponse,
  OperationLogStatsResponse,
  PaginatedOperationLogsResponse,
  PostApiV1AdminMigrationImportBody,
  RevokeRoleRequest,
  RevokeRoleResponse,
  ServerCreateRequest,
  ServerUpdateRequest,
  UpdateRoleRequest,
  UpdateRoleResponse
} from '../models';

import { apiClient } from '../../../lib/api';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Export all configuration data (users, roles, servers, etc.) as an encrypted backup file. Requires admin.system.export permission.
 * @summary Export data
 */
export const getPostApiV1AdminMigrationExportUrl = () => {




  return `/api/v1/admin/migration/export`
}

export const postApiV1AdminMigrationExport = async (exportRequest: ExportRequest, options?: RequestInit): Promise<Blob> => {

  return apiClient<Blob>(getPostApiV1AdminMigrationExportUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      exportRequest,)
  }
);}




export const getPostApiV1AdminMigrationExportMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminMigrationExport>>, TError,{data: ExportRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminMigrationExport>>, TError,{data: ExportRequest}, TContext> => {

const mutationKey = ['postApiV1AdminMigrationExport'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AdminMigrationExport>>, {data: ExportRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AdminMigrationExport(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AdminMigrationExportMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AdminMigrationExport>>>
    export type PostApiV1AdminMigrationExportMutationBody = ExportRequest
    export type PostApiV1AdminMigrationExportMutationError = ErrorResponse | void

    /**
 * @summary Export data
 */
export const usePostApiV1AdminMigrationExport = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminMigrationExport>>, TError,{data: ExportRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AdminMigrationExport>>,
        TError,
        {data: ExportRequest},
        TContext
      > => {
      return useMutation(getPostApiV1AdminMigrationExportMutationOptions(options), queryClient);
    }
    /**
 * Import configuration data from an encrypted backup file. WARNING: This will completely replace all existing data. Requires admin.system.import permission.
 * @summary Import data
 */
export const getPostApiV1AdminMigrationImportUrl = () => {




  return `/api/v1/admin/migration/import`
}

export const postApiV1AdminMigrationImport = async (postApiV1AdminMigrationImportBody: PostApiV1AdminMigrationImportBody, options?: RequestInit): Promise<ImportResponse> => {
    const formData = new FormData();
formData.append(`backup_file`, postApiV1AdminMigrationImportBody.backup_file);
formData.append(`password`, postApiV1AdminMigrationImportBody.password);

  return apiClient<ImportResponse>(getPostApiV1AdminMigrationImportUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body:
      formData,
  }
);}




export const getPostApiV1AdminMigrationImportMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminMigrationImport>>, TError,{data: PostApiV1AdminMigrationImportBody}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminMigrationImport>>, TError,{data: PostApiV1AdminMigrationImportBody}, TContext> => {

const mutationKey = ['postApiV1AdminMigrationImport'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AdminMigrationImport>>, {data: PostApiV1AdminMigrationImportBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AdminMigrationImport(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AdminMigrationImportMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AdminMigrationImport>>>
    export type PostApiV1AdminMigrationImportMutationBody = PostApiV1AdminMigrationImportBody
    export type PostApiV1AdminMigrationImportMutationError = ErrorResponse | void

    /**
 * @summary Import data
 */
export const usePostApiV1AdminMigrationImport = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminMigrationImport>>, TError,{data: PostApiV1AdminMigrationImportBody}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AdminMigrationImport>>,
        TError,
        {data: PostApiV1AdminMigrationImportBody},
        TContext
      > => {
      return useMutation(getPostApiV1AdminMigrationImportMutationOptions(options), queryClient);
    }
    /**
 * Returns paginated list of all operation logs. Requires admin permissions.
 * @summary List all operation logs
 */
export const getGetApiV1AdminOperationLogsUrl = (params?: GetApiV1AdminOperationLogsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/operation-logs?${stringifiedParams}` : `/api/v1/admin/operation-logs`
}

export const getApiV1AdminOperationLogs = async (params?: GetApiV1AdminOperationLogsParams, options?: RequestInit): Promise<PaginatedOperationLogsResponse> => {

  return apiClient<PaginatedOperationLogsResponse>(getGetApiV1AdminOperationLogsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1AdminOperationLogsQueryKey = (params?: GetApiV1AdminOperationLogsParams,) => {
    return [
    `/api/v1/admin/operation-logs`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1AdminOperationLogsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>, TError = ErrorResponse | void>(params?: GetApiV1AdminOperationLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AdminOperationLogsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>> = ({ signal }) => getApiV1AdminOperationLogs(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AdminOperationLogsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>>
export type GetApiV1AdminOperationLogsQueryError = ErrorResponse | void


export function useGetApiV1AdminOperationLogs<TData = Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>, TError = ErrorResponse | void>(
 params: undefined |  GetApiV1AdminOperationLogsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminOperationLogs<TData = Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>, TError = ErrorResponse | void>(
 params?: GetApiV1AdminOperationLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminOperationLogs<TData = Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>, TError = ErrorResponse | void>(
 params?: GetApiV1AdminOperationLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all operation logs
 */

export function useGetApiV1AdminOperationLogs<TData = Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>, TError = ErrorResponse | void>(
 params?: GetApiV1AdminOperationLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AdminOperationLogsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Returns aggregated statistics for all operation logs. Requires admin permissions.
 * @summary Get operation logs statistics
 */
export const getGetApiV1AdminOperationLogsStatsUrl = () => {




  return `/api/v1/admin/operation-logs/stats`
}

export const getApiV1AdminOperationLogsStats = async ( options?: RequestInit): Promise<OperationLogStatsResponse> => {

  return apiClient<OperationLogStatsResponse>(getGetApiV1AdminOperationLogsStatsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1AdminOperationLogsStatsQueryKey = () => {
    return [
    `/api/v1/admin/operation-logs/stats`
    ] as const;
    }


export const getGetApiV1AdminOperationLogsStatsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>, TError = ErrorResponse | void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AdminOperationLogsStatsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>> = ({ signal }) => getApiV1AdminOperationLogsStats({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AdminOperationLogsStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>>
export type GetApiV1AdminOperationLogsStatsQueryError = ErrorResponse | void


export function useGetApiV1AdminOperationLogsStats<TData = Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>, TError = ErrorResponse | void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminOperationLogsStats<TData = Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminOperationLogsStats<TData = Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get operation logs statistics
 */

export function useGetApiV1AdminOperationLogsStats<TData = Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AdminOperationLogsStatsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Returns detailed information about a specific operation log including all messages. Requires admin permissions.
 * @summary Get operation log details
 */
export const getGetApiV1AdminOperationLogsIdUrl = (id: number,) => {




  return `/api/v1/admin/operation-logs/${id}`
}

export const getApiV1AdminOperationLogsId = async (id: number, options?: RequestInit): Promise<OperationLogDetailResponse> => {

  return apiClient<OperationLogDetailResponse>(getGetApiV1AdminOperationLogsIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1AdminOperationLogsIdQueryKey = (id: number,) => {
    return [
    `/api/v1/admin/operation-logs/${id}`
    ] as const;
    }


export const getGetApiV1AdminOperationLogsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>, TError = ErrorResponse | void>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AdminOperationLogsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>> = ({ signal }) => getApiV1AdminOperationLogsId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AdminOperationLogsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>>
export type GetApiV1AdminOperationLogsIdQueryError = ErrorResponse | void


export function useGetApiV1AdminOperationLogsId<TData = Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>, TError = ErrorResponse | void>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminOperationLogsId<TData = Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>, TError = ErrorResponse | void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminOperationLogsId<TData = Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>, TError = ErrorResponse | void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get operation log details
 */

export function useGetApiV1AdminOperationLogsId<TData = Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>, TError = ErrorResponse | void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AdminOperationLogsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Returns list of all permissions. Use ?type=role to filter out API-key-only permissions. Requires admin access.
 * @summary List all permissions
 */
export const getGetApiV1AdminPermissionsUrl = (params?: GetApiV1AdminPermissionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/permissions?${stringifiedParams}` : `/api/v1/admin/permissions`
}

export const getApiV1AdminPermissions = async (params?: GetApiV1AdminPermissionsParams, options?: RequestInit): Promise<ListPermissionsResponse> => {

  return apiClient<ListPermissionsResponse>(getGetApiV1AdminPermissionsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1AdminPermissionsQueryKey = (params?: GetApiV1AdminPermissionsParams,) => {
    return [
    `/api/v1/admin/permissions`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1AdminPermissionsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AdminPermissions>>, TError = ErrorResponse | void>(params?: GetApiV1AdminPermissionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminPermissions>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AdminPermissionsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AdminPermissions>>> = ({ signal }) => getApiV1AdminPermissions(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminPermissions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AdminPermissionsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AdminPermissions>>>
export type GetApiV1AdminPermissionsQueryError = ErrorResponse | void


export function useGetApiV1AdminPermissions<TData = Awaited<ReturnType<typeof getApiV1AdminPermissions>>, TError = ErrorResponse | void>(
 params: undefined |  GetApiV1AdminPermissionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminPermissions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminPermissions>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminPermissions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminPermissions<TData = Awaited<ReturnType<typeof getApiV1AdminPermissions>>, TError = ErrorResponse | void>(
 params?: GetApiV1AdminPermissionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminPermissions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminPermissions>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminPermissions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminPermissions<TData = Awaited<ReturnType<typeof getApiV1AdminPermissions>>, TError = ErrorResponse | void>(
 params?: GetApiV1AdminPermissionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminPermissions>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all permissions
 */

export function useGetApiV1AdminPermissions<TData = Awaited<ReturnType<typeof getApiV1AdminPermissions>>, TError = ErrorResponse | void>(
 params?: GetApiV1AdminPermissionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminPermissions>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AdminPermissionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * List all roles. Requires admin permissions.
 * @summary List all roles
 */
export const getGetApiV1AdminRolesUrl = () => {




  return `/api/v1/admin/roles`
}

export const getApiV1AdminRoles = async ( options?: RequestInit): Promise<ListRolesResponse> => {

  return apiClient<ListRolesResponse>(getGetApiV1AdminRolesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1AdminRolesQueryKey = () => {
    return [
    `/api/v1/admin/roles`
    ] as const;
    }


export const getGetApiV1AdminRolesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AdminRoles>>, TError = ErrorResponse | void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminRoles>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AdminRolesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AdminRoles>>> = ({ signal }) => getApiV1AdminRoles({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminRoles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AdminRolesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AdminRoles>>>
export type GetApiV1AdminRolesQueryError = ErrorResponse | void


export function useGetApiV1AdminRoles<TData = Awaited<ReturnType<typeof getApiV1AdminRoles>>, TError = ErrorResponse | void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminRoles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminRoles>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminRoles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminRoles<TData = Awaited<ReturnType<typeof getApiV1AdminRoles>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminRoles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminRoles>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminRoles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminRoles<TData = Awaited<ReturnType<typeof getApiV1AdminRoles>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminRoles>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all roles
 */

export function useGetApiV1AdminRoles<TData = Awaited<ReturnType<typeof getApiV1AdminRoles>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminRoles>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AdminRolesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Creates a new role. Requires admin permissions.
 * @summary Create a new role
 */
export const getPostApiV1AdminRolesUrl = () => {




  return `/api/v1/admin/roles`
}

export const postApiV1AdminRoles = async (createRoleRequest: CreateRoleRequest, options?: RequestInit): Promise<CreateRoleResponse> => {

  return apiClient<CreateRoleResponse>(getPostApiV1AdminRolesUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createRoleRequest,)
  }
);}




export const getPostApiV1AdminRolesMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminRoles>>, TError,{data: CreateRoleRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminRoles>>, TError,{data: CreateRoleRequest}, TContext> => {

const mutationKey = ['postApiV1AdminRoles'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AdminRoles>>, {data: CreateRoleRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AdminRoles(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AdminRolesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AdminRoles>>>
    export type PostApiV1AdminRolesMutationBody = CreateRoleRequest
    export type PostApiV1AdminRolesMutationError = ErrorResponse | void

    /**
 * @summary Create a new role
 */
export const usePostApiV1AdminRoles = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminRoles>>, TError,{data: CreateRoleRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AdminRoles>>,
        TError,
        {data: CreateRoleRequest},
        TContext
      > => {
      return useMutation(getPostApiV1AdminRolesMutationOptions(options), queryClient);
    }
    /**
 * Deletes a role. Requires admin permissions.
 * @summary Delete a role
 */
export const getDeleteApiV1AdminRolesIdUrl = (id: number,) => {




  return `/api/v1/admin/roles/${id}`
}

export const deleteApiV1AdminRolesId = async (id: number, options?: RequestInit): Promise<DeleteRoleResponse> => {

  return apiClient<DeleteRoleResponse>(getDeleteApiV1AdminRolesIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteApiV1AdminRolesIdMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1AdminRolesId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1AdminRolesId>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteApiV1AdminRolesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1AdminRolesId>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV1AdminRolesId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1AdminRolesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1AdminRolesId>>>

    export type DeleteApiV1AdminRolesIdMutationError = ErrorResponse | void

    /**
 * @summary Delete a role
 */
export const useDeleteApiV1AdminRolesId = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1AdminRolesId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1AdminRolesId>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteApiV1AdminRolesIdMutationOptions(options), queryClient);
    }
    /**
 * Updates an existing role. Requires admin permissions.
 * @summary Update a role
 */
export const getPutApiV1AdminRolesIdUrl = (id: number,) => {




  return `/api/v1/admin/roles/${id}`
}

export const putApiV1AdminRolesId = async (id: number,
    updateRoleRequest: UpdateRoleRequest, options?: RequestInit): Promise<UpdateRoleResponse> => {

  return apiClient<UpdateRoleResponse>(getPutApiV1AdminRolesIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateRoleRequest,)
  }
);}




export const getPutApiV1AdminRolesIdMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1AdminRolesId>>, TError,{id: number;data: UpdateRoleRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV1AdminRolesId>>, TError,{id: number;data: UpdateRoleRequest}, TContext> => {

const mutationKey = ['putApiV1AdminRolesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1AdminRolesId>>, {id: number;data: UpdateRoleRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV1AdminRolesId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiV1AdminRolesIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1AdminRolesId>>>
    export type PutApiV1AdminRolesIdMutationBody = UpdateRoleRequest
    export type PutApiV1AdminRolesIdMutationError = ErrorResponse | void

    /**
 * @summary Update a role
 */
export const usePutApiV1AdminRolesId = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1AdminRolesId>>, TError,{id: number;data: UpdateRoleRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV1AdminRolesId>>,
        TError,
        {id: number;data: UpdateRoleRequest},
        TContext
      > => {
      return useMutation(getPutApiV1AdminRolesIdMutationOptions(options), queryClient);
    }
    /**
 * Returns the role details, available servers, permissions, and current permission rules. Requires admin permissions.
 * @summary List role stack permissions
 */
export const getGetApiV1AdminRolesRoleIdStackPermissionsUrl = (roleId: number,) => {




  return `/api/v1/admin/roles/${roleId}/stack-permissions`
}

export const getApiV1AdminRolesRoleIdStackPermissions = async (roleId: number, options?: RequestInit): Promise<ListRoleStackPermissionsResponse> => {

  return apiClient<ListRoleStackPermissionsResponse>(getGetApiV1AdminRolesRoleIdStackPermissionsUrl(roleId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1AdminRolesRoleIdStackPermissionsQueryKey = (roleId: number,) => {
    return [
    `/api/v1/admin/roles/${roleId}/stack-permissions`
    ] as const;
    }


export const getGetApiV1AdminRolesRoleIdStackPermissionsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>, TError = ErrorResponse | void>(roleId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AdminRolesRoleIdStackPermissionsQueryKey(roleId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>> = ({ signal }) => getApiV1AdminRolesRoleIdStackPermissions(roleId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(roleId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AdminRolesRoleIdStackPermissionsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>>
export type GetApiV1AdminRolesRoleIdStackPermissionsQueryError = ErrorResponse | void


export function useGetApiV1AdminRolesRoleIdStackPermissions<TData = Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>, TError = ErrorResponse | void>(
 roleId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminRolesRoleIdStackPermissions<TData = Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>, TError = ErrorResponse | void>(
 roleId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminRolesRoleIdStackPermissions<TData = Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>, TError = ErrorResponse | void>(
 roleId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List role stack permissions
 */

export function useGetApiV1AdminRolesRoleIdStackPermissions<TData = Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>, TError = ErrorResponse | void>(
 roleId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AdminRolesRoleIdStackPermissionsQueryOptions(roleId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Creates a new permission rule for a role on a server with a stack pattern. Requires admin permissions.
 * @summary Create a role stack permission
 */
export const getPostApiV1AdminRolesRoleIdStackPermissionsUrl = (roleId: number,) => {




  return `/api/v1/admin/roles/${roleId}/stack-permissions`
}

export const postApiV1AdminRolesRoleIdStackPermissions = async (roleId: number,
    createStackPermissionRequest: CreateStackPermissionRequest, options?: RequestInit): Promise<CreateStackPermissionResponse> => {

  return apiClient<CreateStackPermissionResponse>(getPostApiV1AdminRolesRoleIdStackPermissionsUrl(roleId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createStackPermissionRequest,)
  }
);}




export const getPostApiV1AdminRolesRoleIdStackPermissionsMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminRolesRoleIdStackPermissions>>, TError,{roleId: number;data: CreateStackPermissionRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminRolesRoleIdStackPermissions>>, TError,{roleId: number;data: CreateStackPermissionRequest}, TContext> => {

const mutationKey = ['postApiV1AdminRolesRoleIdStackPermissions'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AdminRolesRoleIdStackPermissions>>, {roleId: number;data: CreateStackPermissionRequest}> = (props) => {
          const {roleId,data} = props ?? {};

          return  postApiV1AdminRolesRoleIdStackPermissions(roleId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AdminRolesRoleIdStackPermissionsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AdminRolesRoleIdStackPermissions>>>
    export type PostApiV1AdminRolesRoleIdStackPermissionsMutationBody = CreateStackPermissionRequest
    export type PostApiV1AdminRolesRoleIdStackPermissionsMutationError = ErrorResponse | void

    /**
 * @summary Create a role stack permission
 */
export const usePostApiV1AdminRolesRoleIdStackPermissions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminRolesRoleIdStackPermissions>>, TError,{roleId: number;data: CreateStackPermissionRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AdminRolesRoleIdStackPermissions>>,
        TError,
        {roleId: number;data: CreateStackPermissionRequest},
        TContext
      > => {
      return useMutation(getPostApiV1AdminRolesRoleIdStackPermissionsMutationOptions(options), queryClient);
    }
    /**
 * Deletes a permission rule from a role. Requires admin permissions.
 * @summary Delete a role stack permission
 */
export const getDeleteApiV1AdminRolesRoleIdStackPermissionsPermissionIdUrl = (roleId: number,
    permissionId: number,) => {




  return `/api/v1/admin/roles/${roleId}/stack-permissions/${permissionId}`
}

export const deleteApiV1AdminRolesRoleIdStackPermissionsPermissionId = async (roleId: number,
    permissionId: number, options?: RequestInit): Promise<DeleteStackPermissionResponse> => {

  return apiClient<DeleteStackPermissionResponse>(getDeleteApiV1AdminRolesRoleIdStackPermissionsPermissionIdUrl(roleId,permissionId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteApiV1AdminRolesRoleIdStackPermissionsPermissionIdMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1AdminRolesRoleIdStackPermissionsPermissionId>>, TError,{roleId: number;permissionId: number}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1AdminRolesRoleIdStackPermissionsPermissionId>>, TError,{roleId: number;permissionId: number}, TContext> => {

const mutationKey = ['deleteApiV1AdminRolesRoleIdStackPermissionsPermissionId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1AdminRolesRoleIdStackPermissionsPermissionId>>, {roleId: number;permissionId: number}> = (props) => {
          const {roleId,permissionId} = props ?? {};

          return  deleteApiV1AdminRolesRoleIdStackPermissionsPermissionId(roleId,permissionId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1AdminRolesRoleIdStackPermissionsPermissionIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1AdminRolesRoleIdStackPermissionsPermissionId>>>

    export type DeleteApiV1AdminRolesRoleIdStackPermissionsPermissionIdMutationError = ErrorResponse | void

    /**
 * @summary Delete a role stack permission
 */
export const useDeleteApiV1AdminRolesRoleIdStackPermissionsPermissionId = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1AdminRolesRoleIdStackPermissionsPermissionId>>, TError,{roleId: number;permissionId: number}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1AdminRolesRoleIdStackPermissionsPermissionId>>,
        TError,
        {roleId: number;permissionId: number},
        TContext
      > => {
      return useMutation(getDeleteApiV1AdminRolesRoleIdStackPermissionsPermissionIdMutationOptions(options), queryClient);
    }
    /**
 * Returns paginated list of security audit logs. Requires admin permissions.
 * @summary List security audit logs
 */
export const getGetApiV1AdminSecurityAuditLogsUrl = (params?: GetApiV1AdminSecurityAuditLogsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/security-audit-logs?${stringifiedParams}` : `/api/v1/admin/security-audit-logs`
}

export const getApiV1AdminSecurityAuditLogs = async (params?: GetApiV1AdminSecurityAuditLogsParams, options?: RequestInit): Promise<ListLogsAPIResponse> => {

  return apiClient<ListLogsAPIResponse>(getGetApiV1AdminSecurityAuditLogsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1AdminSecurityAuditLogsQueryKey = (params?: GetApiV1AdminSecurityAuditLogsParams,) => {
    return [
    `/api/v1/admin/security-audit-logs`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1AdminSecurityAuditLogsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>, TError = ErrorResponse | void>(params?: GetApiV1AdminSecurityAuditLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AdminSecurityAuditLogsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>> = ({ signal }) => getApiV1AdminSecurityAuditLogs(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AdminSecurityAuditLogsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>>
export type GetApiV1AdminSecurityAuditLogsQueryError = ErrorResponse | void


export function useGetApiV1AdminSecurityAuditLogs<TData = Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>, TError = ErrorResponse | void>(
 params: undefined |  GetApiV1AdminSecurityAuditLogsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminSecurityAuditLogs<TData = Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>, TError = ErrorResponse | void>(
 params?: GetApiV1AdminSecurityAuditLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminSecurityAuditLogs<TData = Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>, TError = ErrorResponse | void>(
 params?: GetApiV1AdminSecurityAuditLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List security audit logs
 */

export function useGetApiV1AdminSecurityAuditLogs<TData = Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>, TError = ErrorResponse | void>(
 params?: GetApiV1AdminSecurityAuditLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AdminSecurityAuditLogsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Returns aggregated statistics for security audit logs. Requires admin permissions.
 * @summary Get security audit statistics
 */
export const getGetApiV1AdminSecurityAuditLogsStatsUrl = () => {




  return `/api/v1/admin/security-audit-logs/stats`
}

export const getApiV1AdminSecurityAuditLogsStats = async ( options?: RequestInit): Promise<GetStatsAPIResponse> => {

  return apiClient<GetStatsAPIResponse>(getGetApiV1AdminSecurityAuditLogsStatsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1AdminSecurityAuditLogsStatsQueryKey = () => {
    return [
    `/api/v1/admin/security-audit-logs/stats`
    ] as const;
    }


export const getGetApiV1AdminSecurityAuditLogsStatsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>, TError = ErrorResponse | void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AdminSecurityAuditLogsStatsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>> = ({ signal }) => getApiV1AdminSecurityAuditLogsStats({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AdminSecurityAuditLogsStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>>
export type GetApiV1AdminSecurityAuditLogsStatsQueryError = ErrorResponse | void


export function useGetApiV1AdminSecurityAuditLogsStats<TData = Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>, TError = ErrorResponse | void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminSecurityAuditLogsStats<TData = Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminSecurityAuditLogsStats<TData = Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get security audit statistics
 */

export function useGetApiV1AdminSecurityAuditLogsStats<TData = Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AdminSecurityAuditLogsStatsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Returns detailed information about a specific security audit log. Requires admin permissions.
 * @summary Get security audit log details
 */
export const getGetApiV1AdminSecurityAuditLogsIdUrl = (id: number,) => {




  return `/api/v1/admin/security-audit-logs/${id}`
}

export const getApiV1AdminSecurityAuditLogsId = async (id: number, options?: RequestInit): Promise<GetLogAPIResponse> => {

  return apiClient<GetLogAPIResponse>(getGetApiV1AdminSecurityAuditLogsIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1AdminSecurityAuditLogsIdQueryKey = (id: number,) => {
    return [
    `/api/v1/admin/security-audit-logs/${id}`
    ] as const;
    }


export const getGetApiV1AdminSecurityAuditLogsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>, TError = ErrorResponse | void>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AdminSecurityAuditLogsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>> = ({ signal }) => getApiV1AdminSecurityAuditLogsId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AdminSecurityAuditLogsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>>
export type GetApiV1AdminSecurityAuditLogsIdQueryError = ErrorResponse | void


export function useGetApiV1AdminSecurityAuditLogsId<TData = Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>, TError = ErrorResponse | void>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminSecurityAuditLogsId<TData = Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>, TError = ErrorResponse | void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminSecurityAuditLogsId<TData = Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>, TError = ErrorResponse | void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get security audit log details
 */

export function useGetApiV1AdminSecurityAuditLogsId<TData = Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>, TError = ErrorResponse | void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AdminSecurityAuditLogsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Returns list of all servers. Requires admin access.
 * @summary List all servers
 */
export const getGetApiV1AdminServersUrl = () => {




  return `/api/v1/admin/servers`
}

export const getApiV1AdminServers = async ( options?: RequestInit): Promise<AdminListServersResponse> => {

  return apiClient<AdminListServersResponse>(getGetApiV1AdminServersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1AdminServersQueryKey = () => {
    return [
    `/api/v1/admin/servers`
    ] as const;
    }


export const getGetApiV1AdminServersQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AdminServers>>, TError = ErrorResponse | void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminServers>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AdminServersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AdminServers>>> = ({ signal }) => getApiV1AdminServers({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminServers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AdminServersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AdminServers>>>
export type GetApiV1AdminServersQueryError = ErrorResponse | void


export function useGetApiV1AdminServers<TData = Awaited<ReturnType<typeof getApiV1AdminServers>>, TError = ErrorResponse | void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminServers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminServers>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminServers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminServers<TData = Awaited<ReturnType<typeof getApiV1AdminServers>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminServers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminServers>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminServers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminServers<TData = Awaited<ReturnType<typeof getApiV1AdminServers>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminServers>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all servers
 */

export function useGetApiV1AdminServers<TData = Awaited<ReturnType<typeof getApiV1AdminServers>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminServers>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AdminServersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Create a new server connection. Requires admin access.
 * @summary Create a new server
 */
export const getPostApiV1AdminServersUrl = () => {




  return `/api/v1/admin/servers`
}

export const postApiV1AdminServers = async (serverCreateRequest: ServerCreateRequest, options?: RequestInit): Promise<AdminCreateServerResponse> => {

  return apiClient<AdminCreateServerResponse>(getPostApiV1AdminServersUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      serverCreateRequest,)
  }
);}




export const getPostApiV1AdminServersMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminServers>>, TError,{data: ServerCreateRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminServers>>, TError,{data: ServerCreateRequest}, TContext> => {

const mutationKey = ['postApiV1AdminServers'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AdminServers>>, {data: ServerCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AdminServers(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AdminServersMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AdminServers>>>
    export type PostApiV1AdminServersMutationBody = ServerCreateRequest
    export type PostApiV1AdminServersMutationError = ErrorResponse | void

    /**
 * @summary Create a new server
 */
export const usePostApiV1AdminServers = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminServers>>, TError,{data: ServerCreateRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AdminServers>>,
        TError,
        {data: ServerCreateRequest},
        TContext
      > => {
      return useMutation(getPostApiV1AdminServersMutationOptions(options), queryClient);
    }
    /**
 * Delete a server connection. Requires admin access.
 * @summary Delete a server
 */
export const getDeleteApiV1AdminServersIdUrl = (id: number,) => {




  return `/api/v1/admin/servers/${id}`
}

export const deleteApiV1AdminServersId = async (id: number, options?: RequestInit): Promise<AdminDeleteServerResponse> => {

  return apiClient<AdminDeleteServerResponse>(getDeleteApiV1AdminServersIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteApiV1AdminServersIdMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1AdminServersId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1AdminServersId>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteApiV1AdminServersId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1AdminServersId>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV1AdminServersId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1AdminServersIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1AdminServersId>>>

    export type DeleteApiV1AdminServersIdMutationError = ErrorResponse | void

    /**
 * @summary Delete a server
 */
export const useDeleteApiV1AdminServersId = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1AdminServersId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1AdminServersId>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteApiV1AdminServersIdMutationOptions(options), queryClient);
    }
    /**
 * Update an existing server connection. Requires admin access.
 * @summary Update a server
 */
export const getPutApiV1AdminServersIdUrl = (id: number,) => {




  return `/api/v1/admin/servers/${id}`
}

export const putApiV1AdminServersId = async (id: number,
    serverUpdateRequest: ServerUpdateRequest, options?: RequestInit): Promise<AdminUpdateServerResponse> => {

  return apiClient<AdminUpdateServerResponse>(getPutApiV1AdminServersIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      serverUpdateRequest,)
  }
);}




export const getPutApiV1AdminServersIdMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1AdminServersId>>, TError,{id: number;data: ServerUpdateRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV1AdminServersId>>, TError,{id: number;data: ServerUpdateRequest}, TContext> => {

const mutationKey = ['putApiV1AdminServersId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1AdminServersId>>, {id: number;data: ServerUpdateRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV1AdminServersId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiV1AdminServersIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1AdminServersId>>>
    export type PutApiV1AdminServersIdMutationBody = ServerUpdateRequest
    export type PutApiV1AdminServersIdMutationError = ErrorResponse | void

    /**
 * @summary Update a server
 */
export const usePutApiV1AdminServersId = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1AdminServersId>>, TError,{id: number;data: ServerUpdateRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV1AdminServersId>>,
        TError,
        {id: number;data: ServerUpdateRequest},
        TContext
      > => {
      return useMutation(getPutApiV1AdminServersIdMutationOptions(options), queryClient);
    }
    /**
 * Test the connection to a server. Requires admin access.
 * @summary Test server connection
 */
export const getPostApiV1AdminServersIdTestUrl = (id: number,) => {




  return `/api/v1/admin/servers/${id}/test`
}

export const postApiV1AdminServersIdTest = async (id: number, options?: RequestInit): Promise<AdminTestConnectionResponse> => {

  return apiClient<AdminTestConnectionResponse>(getPostApiV1AdminServersIdTestUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostApiV1AdminServersIdTestMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminServersIdTest>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminServersIdTest>>, TError,{id: number}, TContext> => {

const mutationKey = ['postApiV1AdminServersIdTest'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AdminServersIdTest>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  postApiV1AdminServersIdTest(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AdminServersIdTestMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AdminServersIdTest>>>

    export type PostApiV1AdminServersIdTestMutationError = ErrorResponse | void

    /**
 * @summary Test server connection
 */
export const usePostApiV1AdminServersIdTest = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminServersIdTest>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AdminServersIdTest>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getPostApiV1AdminServersIdTestMutationOptions(options), queryClient);
    }
    /**
 * List all users. Requires admin permissions.
 * @summary List all users
 */
export const getGetApiV1AdminUsersUrl = () => {




  return `/api/v1/admin/users`
}

export const getApiV1AdminUsers = async ( options?: RequestInit): Promise<ListUsersResponse> => {

  return apiClient<ListUsersResponse>(getGetApiV1AdminUsersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1AdminUsersQueryKey = () => {
    return [
    `/api/v1/admin/users`
    ] as const;
    }


export const getGetApiV1AdminUsersQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AdminUsers>>, TError = ErrorResponse | void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminUsers>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AdminUsersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AdminUsers>>> = ({ signal }) => getApiV1AdminUsers({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AdminUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AdminUsers>>>
export type GetApiV1AdminUsersQueryError = ErrorResponse | void


export function useGetApiV1AdminUsers<TData = Awaited<ReturnType<typeof getApiV1AdminUsers>>, TError = ErrorResponse | void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminUsers>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminUsers<TData = Awaited<ReturnType<typeof getApiV1AdminUsers>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminUsers>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminUsers<TData = Awaited<ReturnType<typeof getApiV1AdminUsers>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminUsers>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all users
 */

export function useGetApiV1AdminUsers<TData = Awaited<ReturnType<typeof getApiV1AdminUsers>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminUsers>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AdminUsersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Creates a new user account. Requires admin permissions.
 * @summary Create a new user
 */
export const getPostApiV1AdminUsersUrl = () => {




  return `/api/v1/admin/users`
}

export const postApiV1AdminUsers = async (createUserRequest: CreateUserRequest, options?: RequestInit): Promise<CreateUserResponse> => {

  return apiClient<CreateUserResponse>(getPostApiV1AdminUsersUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createUserRequest,)
  }
);}




export const getPostApiV1AdminUsersMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminUsers>>, TError,{data: CreateUserRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminUsers>>, TError,{data: CreateUserRequest}, TContext> => {

const mutationKey = ['postApiV1AdminUsers'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AdminUsers>>, {data: CreateUserRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AdminUsers(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AdminUsersMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AdminUsers>>>
    export type PostApiV1AdminUsersMutationBody = CreateUserRequest
    export type PostApiV1AdminUsersMutationError = ErrorResponse | void

    /**
 * @summary Create a new user
 */
export const usePostApiV1AdminUsers = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminUsers>>, TError,{data: CreateUserRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AdminUsers>>,
        TError,
        {data: CreateUserRequest},
        TContext
      > => {
      return useMutation(getPostApiV1AdminUsersMutationOptions(options), queryClient);
    }
    /**
 * Assigns a role to a user. Requires admin permissions.
 * @summary Assign a role to a user
 */
export const getPostApiV1AdminUsersAssignRoleUrl = () => {




  return `/api/v1/admin/users/assign-role`
}

export const postApiV1AdminUsersAssignRole = async (assignRoleRequest: AssignRoleRequest, options?: RequestInit): Promise<AssignRoleResponse> => {

  return apiClient<AssignRoleResponse>(getPostApiV1AdminUsersAssignRoleUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      assignRoleRequest,)
  }
);}




export const getPostApiV1AdminUsersAssignRoleMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminUsersAssignRole>>, TError,{data: AssignRoleRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminUsersAssignRole>>, TError,{data: AssignRoleRequest}, TContext> => {

const mutationKey = ['postApiV1AdminUsersAssignRole'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AdminUsersAssignRole>>, {data: AssignRoleRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AdminUsersAssignRole(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AdminUsersAssignRoleMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AdminUsersAssignRole>>>
    export type PostApiV1AdminUsersAssignRoleMutationBody = AssignRoleRequest
    export type PostApiV1AdminUsersAssignRoleMutationError = ErrorResponse | void

    /**
 * @summary Assign a role to a user
 */
export const usePostApiV1AdminUsersAssignRole = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminUsersAssignRole>>, TError,{data: AssignRoleRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AdminUsersAssignRole>>,
        TError,
        {data: AssignRoleRequest},
        TContext
      > => {
      return useMutation(getPostApiV1AdminUsersAssignRoleMutationOptions(options), queryClient);
    }
    /**
 * Revokes a role from a user. Requires admin permissions.
 * @summary Revoke a role from a user
 */
export const getPostApiV1AdminUsersRevokeRoleUrl = () => {




  return `/api/v1/admin/users/revoke-role`
}

export const postApiV1AdminUsersRevokeRole = async (revokeRoleRequest: RevokeRoleRequest, options?: RequestInit): Promise<RevokeRoleResponse> => {

  return apiClient<RevokeRoleResponse>(getPostApiV1AdminUsersRevokeRoleUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      revokeRoleRequest,)
  }
);}




export const getPostApiV1AdminUsersRevokeRoleMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminUsersRevokeRole>>, TError,{data: RevokeRoleRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminUsersRevokeRole>>, TError,{data: RevokeRoleRequest}, TContext> => {

const mutationKey = ['postApiV1AdminUsersRevokeRole'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AdminUsersRevokeRole>>, {data: RevokeRoleRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AdminUsersRevokeRole(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AdminUsersRevokeRoleMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AdminUsersRevokeRole>>>
    export type PostApiV1AdminUsersRevokeRoleMutationBody = RevokeRoleRequest
    export type PostApiV1AdminUsersRevokeRoleMutationError = ErrorResponse | void

    /**
 * @summary Revoke a role from a user
 */
export const usePostApiV1AdminUsersRevokeRole = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminUsersRevokeRole>>, TError,{data: RevokeRoleRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AdminUsersRevokeRole>>,
        TError,
        {data: RevokeRoleRequest},
        TContext
      > => {
      return useMutation(getPostApiV1AdminUsersRevokeRoleMutationOptions(options), queryClient);
    }
    /**
 * Returns user details and all available roles. Requires admin permissions.
 * @summary Get user with roles
 */
export const getGetApiV1AdminUsersIdRolesUrl = (id: number,) => {




  return `/api/v1/admin/users/${id}/roles`
}

export const getApiV1AdminUsersIdRoles = async (id: number, options?: RequestInit): Promise<GetUserRolesResponse> => {

  return apiClient<GetUserRolesResponse>(getGetApiV1AdminUsersIdRolesUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1AdminUsersIdRolesQueryKey = (id: number,) => {
    return [
    `/api/v1/admin/users/${id}/roles`
    ] as const;
    }


export const getGetApiV1AdminUsersIdRolesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AdminUsersIdRoles>>, TError = ErrorResponse | void>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminUsersIdRoles>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AdminUsersIdRolesQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AdminUsersIdRoles>>> = ({ signal }) => getApiV1AdminUsersIdRoles(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminUsersIdRoles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AdminUsersIdRolesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AdminUsersIdRoles>>>
export type GetApiV1AdminUsersIdRolesQueryError = ErrorResponse | void


export function useGetApiV1AdminUsersIdRoles<TData = Awaited<ReturnType<typeof getApiV1AdminUsersIdRoles>>, TError = ErrorResponse | void>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminUsersIdRoles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminUsersIdRoles>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminUsersIdRoles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminUsersIdRoles<TData = Awaited<ReturnType<typeof getApiV1AdminUsersIdRoles>>, TError = ErrorResponse | void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminUsersIdRoles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminUsersIdRoles>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminUsersIdRoles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminUsersIdRoles<TData = Awaited<ReturnType<typeof getApiV1AdminUsersIdRoles>>, TError = ErrorResponse | void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminUsersIdRoles>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get user with roles
 */

export function useGetApiV1AdminUsersIdRoles<TData = Awaited<ReturnType<typeof getApiV1AdminUsersIdRoles>>, TError = ErrorResponse | void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminUsersIdRoles>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AdminUsersIdRolesQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




