/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminCreateServerResponse,
  AdminDeleteServerResponse,
  AdminListServersResponse,
  AdminTestConnectionResponse,
  AdminUpdateServerResponse,
  AssignRoleRequest,
  AssignRoleResponse,
  CreateRoleRequest,
  CreateRoleResponse,
  CreateStackPermissionRequest,
  CreateStackPermissionResponse,
  CreateUserRequest,
  CreateUserResponse,
  DeleteRoleResponse,
  DeleteStackPermissionResponse,
  ErrorResponse,
  ExportRequest,
  GetApiV1AdminOperationLogsParams,
  GetApiV1AdminSecurityAuditLogsParams,
  GetLogAPIResponse,
  GetStatsAPIResponse,
  ImportResponse,
  ListLogsAPIResponse,
  ListRoleStackPermissionsResponse,
  ListRolesResponse,
  OperationLogDetail,
  OperationLogStats,
  PaginatedOperationLogs,
  PostApiV1AdminMigrationImportBody,
  RevokeRoleRequest,
  RevokeRoleResponse,
  ServerCreateRequest,
  ServerUpdateRequest,
  UpdateRoleRequest,
  UpdateRoleResponse
} from '.././models';

import { apiClient } from '../../../lib/api';




/**
 * Export all configuration data (users, roles, servers, etc.) as an encrypted backup file. Requires admin.system.export permission.
 * @summary Export data
 */
export const postApiV1AdminMigrationExport = (
    exportRequest: ExportRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<Blob>(
      {url: `/api/v1/admin/migration/export`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: exportRequest,
        responseType: 'blob', signal
    },
      );
    }
  


export const getPostApiV1AdminMigrationExportMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminMigrationExport>>, TError,{data: ExportRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminMigrationExport>>, TError,{data: ExportRequest}, TContext> => {

const mutationKey = ['postApiV1AdminMigrationExport'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AdminMigrationExport>>, {data: ExportRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AdminMigrationExport(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AdminMigrationExportMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AdminMigrationExport>>>
    export type PostApiV1AdminMigrationExportMutationBody = ExportRequest
    export type PostApiV1AdminMigrationExportMutationError = ErrorResponse | void

    /**
 * @summary Export data
 */
export const usePostApiV1AdminMigrationExport = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminMigrationExport>>, TError,{data: ExportRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AdminMigrationExport>>,
        TError,
        {data: ExportRequest},
        TContext
      > => {
      return useMutation(getPostApiV1AdminMigrationExportMutationOptions(options), queryClient);
    }
    /**
 * Import configuration data from an encrypted backup file. WARNING: This will completely replace all existing data. Requires admin.system.import permission.
 * @summary Import data
 */
export const postApiV1AdminMigrationImport = (
    postApiV1AdminMigrationImportBody: PostApiV1AdminMigrationImportBody,
 signal?: AbortSignal
) => {
      
      const formData = new FormData();
formData.append(`backup_file`, postApiV1AdminMigrationImportBody.backup_file);
formData.append(`password`, postApiV1AdminMigrationImportBody.password);

      return apiClient<ImportResponse>(
      {url: `/api/v1/admin/migration/import`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData, signal
    },
      );
    }
  


export const getPostApiV1AdminMigrationImportMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminMigrationImport>>, TError,{data: PostApiV1AdminMigrationImportBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminMigrationImport>>, TError,{data: PostApiV1AdminMigrationImportBody}, TContext> => {

const mutationKey = ['postApiV1AdminMigrationImport'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AdminMigrationImport>>, {data: PostApiV1AdminMigrationImportBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AdminMigrationImport(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AdminMigrationImportMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AdminMigrationImport>>>
    export type PostApiV1AdminMigrationImportMutationBody = PostApiV1AdminMigrationImportBody
    export type PostApiV1AdminMigrationImportMutationError = ErrorResponse | void

    /**
 * @summary Import data
 */
export const usePostApiV1AdminMigrationImport = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminMigrationImport>>, TError,{data: PostApiV1AdminMigrationImportBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AdminMigrationImport>>,
        TError,
        {data: PostApiV1AdminMigrationImportBody},
        TContext
      > => {
      return useMutation(getPostApiV1AdminMigrationImportMutationOptions(options), queryClient);
    }
    /**
 * Returns paginated list of all operation logs. Requires admin permissions.
 * @summary List all operation logs
 */
export const getApiV1AdminOperationLogs = (
    params?: GetApiV1AdminOperationLogsParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<PaginatedOperationLogs>(
      {url: `/api/v1/admin/operation-logs`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiV1AdminOperationLogsQueryKey = (params?: GetApiV1AdminOperationLogsParams,) => {
    return [
    `/api/v1/admin/operation-logs`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetApiV1AdminOperationLogsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>, TError = ErrorResponse | void>(params?: GetApiV1AdminOperationLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AdminOperationLogsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>> = ({ signal }) => getApiV1AdminOperationLogs(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AdminOperationLogsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>>
export type GetApiV1AdminOperationLogsQueryError = ErrorResponse | void


export function useGetApiV1AdminOperationLogs<TData = Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>, TError = ErrorResponse | void>(
 params: undefined |  GetApiV1AdminOperationLogsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminOperationLogs<TData = Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>, TError = ErrorResponse | void>(
 params?: GetApiV1AdminOperationLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminOperationLogs<TData = Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>, TError = ErrorResponse | void>(
 params?: GetApiV1AdminOperationLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all operation logs
 */

export function useGetApiV1AdminOperationLogs<TData = Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>, TError = ErrorResponse | void>(
 params?: GetApiV1AdminOperationLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogs>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AdminOperationLogsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Returns aggregated statistics for all operation logs. Requires admin permissions.
 * @summary Get operation logs statistics
 */
export const getApiV1AdminOperationLogsStats = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<OperationLogStats>(
      {url: `/api/v1/admin/operation-logs/stats`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1AdminOperationLogsStatsQueryKey = () => {
    return [
    `/api/v1/admin/operation-logs/stats`
    ] as const;
    }

    
export const getGetApiV1AdminOperationLogsStatsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>, TError = ErrorResponse | void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AdminOperationLogsStatsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>> = ({ signal }) => getApiV1AdminOperationLogsStats(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AdminOperationLogsStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>>
export type GetApiV1AdminOperationLogsStatsQueryError = ErrorResponse | void


export function useGetApiV1AdminOperationLogsStats<TData = Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>, TError = ErrorResponse | void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminOperationLogsStats<TData = Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminOperationLogsStats<TData = Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get operation logs statistics
 */

export function useGetApiV1AdminOperationLogsStats<TData = Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogsStats>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AdminOperationLogsStatsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Returns detailed information about a specific operation log including all messages. Requires admin permissions.
 * @summary Get operation log details
 */
export const getApiV1AdminOperationLogsId = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return apiClient<OperationLogDetail>(
      {url: `/api/v1/admin/operation-logs/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1AdminOperationLogsIdQueryKey = (id?: number,) => {
    return [
    `/api/v1/admin/operation-logs/${id}`
    ] as const;
    }

    
export const getGetApiV1AdminOperationLogsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>, TError = ErrorResponse | void>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AdminOperationLogsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>> = ({ signal }) => getApiV1AdminOperationLogsId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AdminOperationLogsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>>
export type GetApiV1AdminOperationLogsIdQueryError = ErrorResponse | void


export function useGetApiV1AdminOperationLogsId<TData = Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>, TError = ErrorResponse | void>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminOperationLogsId<TData = Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>, TError = ErrorResponse | void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminOperationLogsId<TData = Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>, TError = ErrorResponse | void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get operation log details
 */

export function useGetApiV1AdminOperationLogsId<TData = Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>, TError = ErrorResponse | void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminOperationLogsId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AdminOperationLogsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * List all roles. Requires admin permissions.
 * @summary List all roles
 */
export const getApiV1AdminRoles = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<ListRolesResponse>(
      {url: `/api/v1/admin/roles`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1AdminRolesQueryKey = () => {
    return [
    `/api/v1/admin/roles`
    ] as const;
    }

    
export const getGetApiV1AdminRolesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AdminRoles>>, TError = ErrorResponse | void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminRoles>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AdminRolesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AdminRoles>>> = ({ signal }) => getApiV1AdminRoles(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminRoles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AdminRolesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AdminRoles>>>
export type GetApiV1AdminRolesQueryError = ErrorResponse | void


export function useGetApiV1AdminRoles<TData = Awaited<ReturnType<typeof getApiV1AdminRoles>>, TError = ErrorResponse | void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminRoles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminRoles>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminRoles>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminRoles<TData = Awaited<ReturnType<typeof getApiV1AdminRoles>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminRoles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminRoles>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminRoles>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminRoles<TData = Awaited<ReturnType<typeof getApiV1AdminRoles>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminRoles>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all roles
 */

export function useGetApiV1AdminRoles<TData = Awaited<ReturnType<typeof getApiV1AdminRoles>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminRoles>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AdminRolesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Creates a new role. Requires admin permissions.
 * @summary Create a new role
 */
export const postApiV1AdminRoles = (
    createRoleRequest: CreateRoleRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<CreateRoleResponse>(
      {url: `/api/v1/admin/roles`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createRoleRequest, signal
    },
      );
    }
  


export const getPostApiV1AdminRolesMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminRoles>>, TError,{data: CreateRoleRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminRoles>>, TError,{data: CreateRoleRequest}, TContext> => {

const mutationKey = ['postApiV1AdminRoles'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AdminRoles>>, {data: CreateRoleRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AdminRoles(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AdminRolesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AdminRoles>>>
    export type PostApiV1AdminRolesMutationBody = CreateRoleRequest
    export type PostApiV1AdminRolesMutationError = ErrorResponse | void

    /**
 * @summary Create a new role
 */
export const usePostApiV1AdminRoles = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminRoles>>, TError,{data: CreateRoleRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AdminRoles>>,
        TError,
        {data: CreateRoleRequest},
        TContext
      > => {
      return useMutation(getPostApiV1AdminRolesMutationOptions(options), queryClient);
    }
    /**
 * Deletes a role. Requires admin permissions.
 * @summary Delete a role
 */
export const deleteApiV1AdminRolesId = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return apiClient<DeleteRoleResponse>(
      {url: `/api/v1/admin/roles/${id}`, method: 'DELETE', signal
    },
      );
    }
  


export const getDeleteApiV1AdminRolesIdMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1AdminRolesId>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1AdminRolesId>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteApiV1AdminRolesId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1AdminRolesId>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV1AdminRolesId(id,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1AdminRolesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1AdminRolesId>>>
    
    export type DeleteApiV1AdminRolesIdMutationError = ErrorResponse | void

    /**
 * @summary Delete a role
 */
export const useDeleteApiV1AdminRolesId = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1AdminRolesId>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1AdminRolesId>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteApiV1AdminRolesIdMutationOptions(options), queryClient);
    }
    /**
 * Updates an existing role. Requires admin permissions.
 * @summary Update a role
 */
export const putApiV1AdminRolesId = (
    id: number,
    updateRoleRequest: UpdateRoleRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<UpdateRoleResponse>(
      {url: `/api/v1/admin/roles/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateRoleRequest, signal
    },
      );
    }
  


export const getPutApiV1AdminRolesIdMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1AdminRolesId>>, TError,{id: number;data: UpdateRoleRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiV1AdminRolesId>>, TError,{id: number;data: UpdateRoleRequest}, TContext> => {

const mutationKey = ['putApiV1AdminRolesId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1AdminRolesId>>, {id: number;data: UpdateRoleRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV1AdminRolesId(id,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV1AdminRolesIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1AdminRolesId>>>
    export type PutApiV1AdminRolesIdMutationBody = UpdateRoleRequest
    export type PutApiV1AdminRolesIdMutationError = ErrorResponse | void

    /**
 * @summary Update a role
 */
export const usePutApiV1AdminRolesId = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1AdminRolesId>>, TError,{id: number;data: UpdateRoleRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV1AdminRolesId>>,
        TError,
        {id: number;data: UpdateRoleRequest},
        TContext
      > => {
      return useMutation(getPutApiV1AdminRolesIdMutationOptions(options), queryClient);
    }
    /**
 * Returns the role details, available servers, permissions, and current permission rules. Requires admin permissions.
 * @summary List role stack permissions
 */
export const getApiV1AdminRolesRoleIdStackPermissions = (
    roleId: number,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ListRoleStackPermissionsResponse>(
      {url: `/api/v1/admin/roles/${roleId}/stack-permissions`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1AdminRolesRoleIdStackPermissionsQueryKey = (roleId?: number,) => {
    return [
    `/api/v1/admin/roles/${roleId}/stack-permissions`
    ] as const;
    }

    
export const getGetApiV1AdminRolesRoleIdStackPermissionsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>, TError = ErrorResponse | void>(roleId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AdminRolesRoleIdStackPermissionsQueryKey(roleId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>> = ({ signal }) => getApiV1AdminRolesRoleIdStackPermissions(roleId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(roleId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AdminRolesRoleIdStackPermissionsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>>
export type GetApiV1AdminRolesRoleIdStackPermissionsQueryError = ErrorResponse | void


export function useGetApiV1AdminRolesRoleIdStackPermissions<TData = Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>, TError = ErrorResponse | void>(
 roleId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminRolesRoleIdStackPermissions<TData = Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>, TError = ErrorResponse | void>(
 roleId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminRolesRoleIdStackPermissions<TData = Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>, TError = ErrorResponse | void>(
 roleId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List role stack permissions
 */

export function useGetApiV1AdminRolesRoleIdStackPermissions<TData = Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>, TError = ErrorResponse | void>(
 roleId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminRolesRoleIdStackPermissions>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AdminRolesRoleIdStackPermissionsQueryOptions(roleId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Creates a new permission rule for a role on a server with a stack pattern. Requires admin permissions.
 * @summary Create a role stack permission
 */
export const postApiV1AdminRolesRoleIdStackPermissions = (
    roleId: number,
    createStackPermissionRequest: CreateStackPermissionRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<CreateStackPermissionResponse>(
      {url: `/api/v1/admin/roles/${roleId}/stack-permissions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createStackPermissionRequest, signal
    },
      );
    }
  


export const getPostApiV1AdminRolesRoleIdStackPermissionsMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminRolesRoleIdStackPermissions>>, TError,{roleId: number;data: CreateStackPermissionRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminRolesRoleIdStackPermissions>>, TError,{roleId: number;data: CreateStackPermissionRequest}, TContext> => {

const mutationKey = ['postApiV1AdminRolesRoleIdStackPermissions'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AdminRolesRoleIdStackPermissions>>, {roleId: number;data: CreateStackPermissionRequest}> = (props) => {
          const {roleId,data} = props ?? {};

          return  postApiV1AdminRolesRoleIdStackPermissions(roleId,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AdminRolesRoleIdStackPermissionsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AdminRolesRoleIdStackPermissions>>>
    export type PostApiV1AdminRolesRoleIdStackPermissionsMutationBody = CreateStackPermissionRequest
    export type PostApiV1AdminRolesRoleIdStackPermissionsMutationError = ErrorResponse | void

    /**
 * @summary Create a role stack permission
 */
export const usePostApiV1AdminRolesRoleIdStackPermissions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminRolesRoleIdStackPermissions>>, TError,{roleId: number;data: CreateStackPermissionRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AdminRolesRoleIdStackPermissions>>,
        TError,
        {roleId: number;data: CreateStackPermissionRequest},
        TContext
      > => {
      return useMutation(getPostApiV1AdminRolesRoleIdStackPermissionsMutationOptions(options), queryClient);
    }
    /**
 * Deletes a permission rule from a role. Requires admin permissions.
 * @summary Delete a role stack permission
 */
export const deleteApiV1AdminRolesRoleIdStackPermissionsPermissionId = (
    roleId: number,
    permissionId: number,
 signal?: AbortSignal
) => {
      
      
      return apiClient<DeleteStackPermissionResponse>(
      {url: `/api/v1/admin/roles/${roleId}/stack-permissions/${permissionId}`, method: 'DELETE', signal
    },
      );
    }
  


export const getDeleteApiV1AdminRolesRoleIdStackPermissionsPermissionIdMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1AdminRolesRoleIdStackPermissionsPermissionId>>, TError,{roleId: number;permissionId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1AdminRolesRoleIdStackPermissionsPermissionId>>, TError,{roleId: number;permissionId: number}, TContext> => {

const mutationKey = ['deleteApiV1AdminRolesRoleIdStackPermissionsPermissionId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1AdminRolesRoleIdStackPermissionsPermissionId>>, {roleId: number;permissionId: number}> = (props) => {
          const {roleId,permissionId} = props ?? {};

          return  deleteApiV1AdminRolesRoleIdStackPermissionsPermissionId(roleId,permissionId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1AdminRolesRoleIdStackPermissionsPermissionIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1AdminRolesRoleIdStackPermissionsPermissionId>>>
    
    export type DeleteApiV1AdminRolesRoleIdStackPermissionsPermissionIdMutationError = ErrorResponse | void

    /**
 * @summary Delete a role stack permission
 */
export const useDeleteApiV1AdminRolesRoleIdStackPermissionsPermissionId = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1AdminRolesRoleIdStackPermissionsPermissionId>>, TError,{roleId: number;permissionId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1AdminRolesRoleIdStackPermissionsPermissionId>>,
        TError,
        {roleId: number;permissionId: number},
        TContext
      > => {
      return useMutation(getDeleteApiV1AdminRolesRoleIdStackPermissionsPermissionIdMutationOptions(options), queryClient);
    }
    /**
 * Returns paginated list of security audit logs. Requires admin permissions.
 * @summary List security audit logs
 */
export const getApiV1AdminSecurityAuditLogs = (
    params?: GetApiV1AdminSecurityAuditLogsParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ListLogsAPIResponse>(
      {url: `/api/v1/admin/security-audit-logs`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiV1AdminSecurityAuditLogsQueryKey = (params?: GetApiV1AdminSecurityAuditLogsParams,) => {
    return [
    `/api/v1/admin/security-audit-logs`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetApiV1AdminSecurityAuditLogsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>, TError = ErrorResponse | void>(params?: GetApiV1AdminSecurityAuditLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AdminSecurityAuditLogsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>> = ({ signal }) => getApiV1AdminSecurityAuditLogs(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AdminSecurityAuditLogsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>>
export type GetApiV1AdminSecurityAuditLogsQueryError = ErrorResponse | void


export function useGetApiV1AdminSecurityAuditLogs<TData = Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>, TError = ErrorResponse | void>(
 params: undefined |  GetApiV1AdminSecurityAuditLogsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminSecurityAuditLogs<TData = Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>, TError = ErrorResponse | void>(
 params?: GetApiV1AdminSecurityAuditLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminSecurityAuditLogs<TData = Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>, TError = ErrorResponse | void>(
 params?: GetApiV1AdminSecurityAuditLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List security audit logs
 */

export function useGetApiV1AdminSecurityAuditLogs<TData = Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>, TError = ErrorResponse | void>(
 params?: GetApiV1AdminSecurityAuditLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogs>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AdminSecurityAuditLogsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Returns aggregated statistics for security audit logs. Requires admin permissions.
 * @summary Get security audit statistics
 */
export const getApiV1AdminSecurityAuditLogsStats = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<GetStatsAPIResponse>(
      {url: `/api/v1/admin/security-audit-logs/stats`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1AdminSecurityAuditLogsStatsQueryKey = () => {
    return [
    `/api/v1/admin/security-audit-logs/stats`
    ] as const;
    }

    
export const getGetApiV1AdminSecurityAuditLogsStatsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>, TError = ErrorResponse | void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AdminSecurityAuditLogsStatsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>> = ({ signal }) => getApiV1AdminSecurityAuditLogsStats(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AdminSecurityAuditLogsStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>>
export type GetApiV1AdminSecurityAuditLogsStatsQueryError = ErrorResponse | void


export function useGetApiV1AdminSecurityAuditLogsStats<TData = Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>, TError = ErrorResponse | void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminSecurityAuditLogsStats<TData = Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminSecurityAuditLogsStats<TData = Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get security audit statistics
 */

export function useGetApiV1AdminSecurityAuditLogsStats<TData = Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsStats>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AdminSecurityAuditLogsStatsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Returns detailed information about a specific security audit log. Requires admin permissions.
 * @summary Get security audit log details
 */
export const getApiV1AdminSecurityAuditLogsId = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return apiClient<GetLogAPIResponse>(
      {url: `/api/v1/admin/security-audit-logs/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1AdminSecurityAuditLogsIdQueryKey = (id?: number,) => {
    return [
    `/api/v1/admin/security-audit-logs/${id}`
    ] as const;
    }

    
export const getGetApiV1AdminSecurityAuditLogsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>, TError = ErrorResponse | void>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AdminSecurityAuditLogsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>> = ({ signal }) => getApiV1AdminSecurityAuditLogsId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AdminSecurityAuditLogsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>>
export type GetApiV1AdminSecurityAuditLogsIdQueryError = ErrorResponse | void


export function useGetApiV1AdminSecurityAuditLogsId<TData = Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>, TError = ErrorResponse | void>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminSecurityAuditLogsId<TData = Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>, TError = ErrorResponse | void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminSecurityAuditLogsId<TData = Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>, TError = ErrorResponse | void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get security audit log details
 */

export function useGetApiV1AdminSecurityAuditLogsId<TData = Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>, TError = ErrorResponse | void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminSecurityAuditLogsId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AdminSecurityAuditLogsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Returns list of all servers. Requires admin access.
 * @summary List all servers
 */
export const getApiV1AdminServers = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<AdminListServersResponse>(
      {url: `/api/v1/admin/servers`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1AdminServersQueryKey = () => {
    return [
    `/api/v1/admin/servers`
    ] as const;
    }

    
export const getGetApiV1AdminServersQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AdminServers>>, TError = ErrorResponse | void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminServers>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AdminServersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AdminServers>>> = ({ signal }) => getApiV1AdminServers(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminServers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AdminServersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AdminServers>>>
export type GetApiV1AdminServersQueryError = ErrorResponse | void


export function useGetApiV1AdminServers<TData = Awaited<ReturnType<typeof getApiV1AdminServers>>, TError = ErrorResponse | void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminServers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminServers>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminServers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminServers<TData = Awaited<ReturnType<typeof getApiV1AdminServers>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminServers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminServers>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminServers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminServers<TData = Awaited<ReturnType<typeof getApiV1AdminServers>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminServers>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all servers
 */

export function useGetApiV1AdminServers<TData = Awaited<ReturnType<typeof getApiV1AdminServers>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminServers>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AdminServersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Create a new server connection. Requires admin access.
 * @summary Create a new server
 */
export const postApiV1AdminServers = (
    serverCreateRequest: ServerCreateRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<AdminCreateServerResponse>(
      {url: `/api/v1/admin/servers`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: serverCreateRequest, signal
    },
      );
    }
  


export const getPostApiV1AdminServersMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminServers>>, TError,{data: ServerCreateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminServers>>, TError,{data: ServerCreateRequest}, TContext> => {

const mutationKey = ['postApiV1AdminServers'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AdminServers>>, {data: ServerCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AdminServers(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AdminServersMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AdminServers>>>
    export type PostApiV1AdminServersMutationBody = ServerCreateRequest
    export type PostApiV1AdminServersMutationError = ErrorResponse | void

    /**
 * @summary Create a new server
 */
export const usePostApiV1AdminServers = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminServers>>, TError,{data: ServerCreateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AdminServers>>,
        TError,
        {data: ServerCreateRequest},
        TContext
      > => {
      return useMutation(getPostApiV1AdminServersMutationOptions(options), queryClient);
    }
    /**
 * Delete a server connection. Requires admin access.
 * @summary Delete a server
 */
export const deleteApiV1AdminServersId = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return apiClient<AdminDeleteServerResponse>(
      {url: `/api/v1/admin/servers/${id}`, method: 'DELETE', signal
    },
      );
    }
  


export const getDeleteApiV1AdminServersIdMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1AdminServersId>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1AdminServersId>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteApiV1AdminServersId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1AdminServersId>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV1AdminServersId(id,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1AdminServersIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1AdminServersId>>>
    
    export type DeleteApiV1AdminServersIdMutationError = ErrorResponse | void

    /**
 * @summary Delete a server
 */
export const useDeleteApiV1AdminServersId = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1AdminServersId>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1AdminServersId>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteApiV1AdminServersIdMutationOptions(options), queryClient);
    }
    /**
 * Update an existing server connection. Requires admin access.
 * @summary Update a server
 */
export const putApiV1AdminServersId = (
    id: number,
    serverUpdateRequest: ServerUpdateRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<AdminUpdateServerResponse>(
      {url: `/api/v1/admin/servers/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: serverUpdateRequest, signal
    },
      );
    }
  


export const getPutApiV1AdminServersIdMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1AdminServersId>>, TError,{id: number;data: ServerUpdateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiV1AdminServersId>>, TError,{id: number;data: ServerUpdateRequest}, TContext> => {

const mutationKey = ['putApiV1AdminServersId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1AdminServersId>>, {id: number;data: ServerUpdateRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV1AdminServersId(id,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV1AdminServersIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1AdminServersId>>>
    export type PutApiV1AdminServersIdMutationBody = ServerUpdateRequest
    export type PutApiV1AdminServersIdMutationError = ErrorResponse | void

    /**
 * @summary Update a server
 */
export const usePutApiV1AdminServersId = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1AdminServersId>>, TError,{id: number;data: ServerUpdateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV1AdminServersId>>,
        TError,
        {id: number;data: ServerUpdateRequest},
        TContext
      > => {
      return useMutation(getPutApiV1AdminServersIdMutationOptions(options), queryClient);
    }
    /**
 * Test the connection to a server. Requires admin access.
 * @summary Test server connection
 */
export const postApiV1AdminServersIdTest = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return apiClient<AdminTestConnectionResponse>(
      {url: `/api/v1/admin/servers/${id}/test`, method: 'POST', signal
    },
      );
    }
  


export const getPostApiV1AdminServersIdTestMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminServersIdTest>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminServersIdTest>>, TError,{id: number}, TContext> => {

const mutationKey = ['postApiV1AdminServersIdTest'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AdminServersIdTest>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  postApiV1AdminServersIdTest(id,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AdminServersIdTestMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AdminServersIdTest>>>
    
    export type PostApiV1AdminServersIdTestMutationError = ErrorResponse | void

    /**
 * @summary Test server connection
 */
export const usePostApiV1AdminServersIdTest = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminServersIdTest>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AdminServersIdTest>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getPostApiV1AdminServersIdTestMutationOptions(options), queryClient);
    }
    /**
 * Creates a new user account. Requires admin permissions.
 * @summary Create a new user
 */
export const postApiV1AdminUsers = (
    createUserRequest: CreateUserRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<CreateUserResponse>(
      {url: `/api/v1/admin/users`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createUserRequest, signal
    },
      );
    }
  


export const getPostApiV1AdminUsersMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminUsers>>, TError,{data: CreateUserRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminUsers>>, TError,{data: CreateUserRequest}, TContext> => {

const mutationKey = ['postApiV1AdminUsers'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AdminUsers>>, {data: CreateUserRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AdminUsers(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AdminUsersMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AdminUsers>>>
    export type PostApiV1AdminUsersMutationBody = CreateUserRequest
    export type PostApiV1AdminUsersMutationError = ErrorResponse | void

    /**
 * @summary Create a new user
 */
export const usePostApiV1AdminUsers = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminUsers>>, TError,{data: CreateUserRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AdminUsers>>,
        TError,
        {data: CreateUserRequest},
        TContext
      > => {
      return useMutation(getPostApiV1AdminUsersMutationOptions(options), queryClient);
    }
    /**
 * Assigns a role to a user. Requires admin permissions.
 * @summary Assign a role to a user
 */
export const postApiV1AdminUsersAssignRole = (
    assignRoleRequest: AssignRoleRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<AssignRoleResponse>(
      {url: `/api/v1/admin/users/assign-role`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: assignRoleRequest, signal
    },
      );
    }
  


export const getPostApiV1AdminUsersAssignRoleMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminUsersAssignRole>>, TError,{data: AssignRoleRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminUsersAssignRole>>, TError,{data: AssignRoleRequest}, TContext> => {

const mutationKey = ['postApiV1AdminUsersAssignRole'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AdminUsersAssignRole>>, {data: AssignRoleRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AdminUsersAssignRole(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AdminUsersAssignRoleMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AdminUsersAssignRole>>>
    export type PostApiV1AdminUsersAssignRoleMutationBody = AssignRoleRequest
    export type PostApiV1AdminUsersAssignRoleMutationError = ErrorResponse | void

    /**
 * @summary Assign a role to a user
 */
export const usePostApiV1AdminUsersAssignRole = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminUsersAssignRole>>, TError,{data: AssignRoleRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AdminUsersAssignRole>>,
        TError,
        {data: AssignRoleRequest},
        TContext
      > => {
      return useMutation(getPostApiV1AdminUsersAssignRoleMutationOptions(options), queryClient);
    }
    /**
 * Revokes a role from a user. Requires admin permissions.
 * @summary Revoke a role from a user
 */
export const postApiV1AdminUsersRevokeRole = (
    revokeRoleRequest: RevokeRoleRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<RevokeRoleResponse>(
      {url: `/api/v1/admin/users/revoke-role`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: revokeRoleRequest, signal
    },
      );
    }
  


export const getPostApiV1AdminUsersRevokeRoleMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminUsersRevokeRole>>, TError,{data: RevokeRoleRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminUsersRevokeRole>>, TError,{data: RevokeRoleRequest}, TContext> => {

const mutationKey = ['postApiV1AdminUsersRevokeRole'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AdminUsersRevokeRole>>, {data: RevokeRoleRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AdminUsersRevokeRole(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AdminUsersRevokeRoleMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AdminUsersRevokeRole>>>
    export type PostApiV1AdminUsersRevokeRoleMutationBody = RevokeRoleRequest
    export type PostApiV1AdminUsersRevokeRoleMutationError = ErrorResponse | void

    /**
 * @summary Revoke a role from a user
 */
export const usePostApiV1AdminUsersRevokeRole = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminUsersRevokeRole>>, TError,{data: RevokeRoleRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AdminUsersRevokeRole>>,
        TError,
        {data: RevokeRoleRequest},
        TContext
      > => {
      return useMutation(getPostApiV1AdminUsersRevokeRoleMutationOptions(options), queryClient);
    }
    