/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  TOTPDisableRequest,
  TOTPEnableRequest,
  TOTPMessageResponse,
  TOTPSetupResponse,
  TOTPStatusResponse
} from '.././models';

import { apiClient } from '../../../lib/api';




/**
 * Disables two-factor authentication. Requires both the current TOTP code and password for security.
 * @summary Disable TOTP
 */
export const postApiV1TotpDisable = (
    tOTPDisableRequest: TOTPDisableRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<TOTPMessageResponse>(
      {url: `/api/v1/totp/disable`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: tOTPDisableRequest, signal
    },
      );
    }
  


export const getPostApiV1TotpDisableMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TotpDisable>>, TError,{data: TOTPDisableRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1TotpDisable>>, TError,{data: TOTPDisableRequest}, TContext> => {

const mutationKey = ['postApiV1TotpDisable'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1TotpDisable>>, {data: TOTPDisableRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1TotpDisable(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1TotpDisableMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1TotpDisable>>>
    export type PostApiV1TotpDisableMutationBody = TOTPDisableRequest
    export type PostApiV1TotpDisableMutationError = ErrorResponse | void

    /**
 * @summary Disable TOTP
 */
export const usePostApiV1TotpDisable = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TotpDisable>>, TError,{data: TOTPDisableRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1TotpDisable>>,
        TError,
        {data: TOTPDisableRequest},
        TContext
      > => {
      return useMutation(getPostApiV1TotpDisableMutationOptions(options), queryClient);
    }
    /**
 * Enables two-factor authentication after verifying the TOTP code from the authenticator app.
 * @summary Enable TOTP
 */
export const postApiV1TotpEnable = (
    tOTPEnableRequest: TOTPEnableRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<TOTPMessageResponse>(
      {url: `/api/v1/totp/enable`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: tOTPEnableRequest, signal
    },
      );
    }
  


export const getPostApiV1TotpEnableMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TotpEnable>>, TError,{data: TOTPEnableRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1TotpEnable>>, TError,{data: TOTPEnableRequest}, TContext> => {

const mutationKey = ['postApiV1TotpEnable'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1TotpEnable>>, {data: TOTPEnableRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1TotpEnable(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1TotpEnableMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1TotpEnable>>>
    export type PostApiV1TotpEnableMutationBody = TOTPEnableRequest
    export type PostApiV1TotpEnableMutationError = ErrorResponse | void

    /**
 * @summary Enable TOTP
 */
export const usePostApiV1TotpEnable = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TotpEnable>>, TError,{data: TOTPEnableRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1TotpEnable>>,
        TError,
        {data: TOTPEnableRequest},
        TContext
      > => {
      return useMutation(getPostApiV1TotpEnableMutationOptions(options), queryClient);
    }
    /**
 * Returns the QR code URI and secret for setting up two-factor authentication. Only available if TOTP is not already enabled.
 * @summary Get TOTP setup information
 */
export const getApiV1TotpSetup = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<TOTPSetupResponse>(
      {url: `/api/v1/totp/setup`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1TotpSetupQueryKey = () => {
    return [
    `/api/v1/totp/setup`
    ] as const;
    }

    
export const getGetApiV1TotpSetupQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TotpSetup>>, TError = ErrorResponse | void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TotpSetup>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TotpSetupQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TotpSetup>>> = ({ signal }) => getApiV1TotpSetup(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TotpSetup>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1TotpSetupQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TotpSetup>>>
export type GetApiV1TotpSetupQueryError = ErrorResponse | void


export function useGetApiV1TotpSetup<TData = Awaited<ReturnType<typeof getApiV1TotpSetup>>, TError = ErrorResponse | void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TotpSetup>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TotpSetup>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TotpSetup>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TotpSetup<TData = Awaited<ReturnType<typeof getApiV1TotpSetup>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TotpSetup>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TotpSetup>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TotpSetup>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TotpSetup<TData = Awaited<ReturnType<typeof getApiV1TotpSetup>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TotpSetup>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get TOTP setup information
 */

export function useGetApiV1TotpSetup<TData = Awaited<ReturnType<typeof getApiV1TotpSetup>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TotpSetup>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1TotpSetupQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Returns whether two-factor authentication is enabled for the authenticated user.
 * @summary Get TOTP status
 */
export const getApiV1TotpStatus = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<TOTPStatusResponse>(
      {url: `/api/v1/totp/status`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1TotpStatusQueryKey = () => {
    return [
    `/api/v1/totp/status`
    ] as const;
    }

    
export const getGetApiV1TotpStatusQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TotpStatus>>, TError = ErrorResponse | void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TotpStatus>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TotpStatusQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TotpStatus>>> = ({ signal }) => getApiV1TotpStatus(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TotpStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1TotpStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TotpStatus>>>
export type GetApiV1TotpStatusQueryError = ErrorResponse | void


export function useGetApiV1TotpStatus<TData = Awaited<ReturnType<typeof getApiV1TotpStatus>>, TError = ErrorResponse | void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TotpStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TotpStatus>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TotpStatus>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TotpStatus<TData = Awaited<ReturnType<typeof getApiV1TotpStatus>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TotpStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TotpStatus>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TotpStatus>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TotpStatus<TData = Awaited<ReturnType<typeof getApiV1TotpStatus>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TotpStatus>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get TOTP status
 */

export function useGetApiV1TotpStatus<TData = Awaited<ReturnType<typeof getApiV1TotpStatus>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TotpStatus>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1TotpStatusQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




