/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  ImageUpdatesResponse
} from '.././models';

import { apiClient } from '../../../lib/api';




/**
 * Returns all container images with available updates across servers the user can access
 * @summary List available image updates
 */
export const getApiV1ImageUpdates = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<ImageUpdatesResponse>(
      {url: `/api/v1/image-updates`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1ImageUpdatesQueryKey = () => {
    return [
    `/api/v1/image-updates`
    ] as const;
    }

    
export const getGetApiV1ImageUpdatesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ImageUpdates>>, TError = ErrorResponse | void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ImageUpdates>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ImageUpdatesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ImageUpdates>>> = ({ signal }) => getApiV1ImageUpdates(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ImageUpdates>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ImageUpdatesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ImageUpdates>>>
export type GetApiV1ImageUpdatesQueryError = ErrorResponse | void


export function useGetApiV1ImageUpdates<TData = Awaited<ReturnType<typeof getApiV1ImageUpdates>>, TError = ErrorResponse | void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ImageUpdates>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ImageUpdates>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ImageUpdates>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ImageUpdates<TData = Awaited<ReturnType<typeof getApiV1ImageUpdates>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ImageUpdates>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ImageUpdates>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ImageUpdates>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ImageUpdates<TData = Awaited<ReturnType<typeof getApiV1ImageUpdates>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ImageUpdates>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List available image updates
 */

export function useGetApiV1ImageUpdates<TData = Awaited<ReturnType<typeof getApiV1ImageUpdates>>, TError = ErrorResponse | void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ImageUpdates>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ImageUpdatesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Returns container images with available updates for a specific server
 * @summary List server image updates
 */
export const getApiV1ServersServeridImageUpdates = (
    serverid: number,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ImageUpdatesResponse>(
      {url: `/api/v1/servers/${serverid}/image-updates`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1ServersServeridImageUpdatesQueryKey = (serverid?: number,) => {
    return [
    `/api/v1/servers/${serverid}/image-updates`
    ] as const;
    }

    
export const getGetApiV1ServersServeridImageUpdatesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ServersServeridImageUpdates>>, TError = ErrorResponse | void>(serverid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridImageUpdates>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ServersServeridImageUpdatesQueryKey(serverid);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ServersServeridImageUpdates>>> = ({ signal }) => getApiV1ServersServeridImageUpdates(serverid, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(serverid), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridImageUpdates>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ServersServeridImageUpdatesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ServersServeridImageUpdates>>>
export type GetApiV1ServersServeridImageUpdatesQueryError = ErrorResponse | void


export function useGetApiV1ServersServeridImageUpdates<TData = Awaited<ReturnType<typeof getApiV1ServersServeridImageUpdates>>, TError = ErrorResponse | void>(
 serverid: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridImageUpdates>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ServersServeridImageUpdates>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ServersServeridImageUpdates>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ServersServeridImageUpdates<TData = Awaited<ReturnType<typeof getApiV1ServersServeridImageUpdates>>, TError = ErrorResponse | void>(
 serverid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridImageUpdates>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ServersServeridImageUpdates>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ServersServeridImageUpdates>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ServersServeridImageUpdates<TData = Awaited<ReturnType<typeof getApiV1ServersServeridImageUpdates>>, TError = ErrorResponse | void>(
 serverid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridImageUpdates>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List server image updates
 */

export function useGetApiV1ServersServeridImageUpdates<TData = Awaited<ReturnType<typeof getApiV1ServersServeridImageUpdates>>, TError = ErrorResponse | void>(
 serverid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridImageUpdates>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ServersServeridImageUpdatesQueryOptions(serverid,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




