/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CompareScanResponse,
  ErrorResponse,
  GetApiV1ServersServeridStacksStacknameVulnscanTrendParams,
  GetLatestScanResponse,
  GetScanResponse,
  GetScanSummaryResponse,
  GetScanTrendResponse,
  GetScansHistoryResponse,
  StartScanRequest,
  StartScanResponse
} from '../models';

import { apiClient } from '../../../lib/api';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns the most recent vulnerability scan and summary for a stack. Requires stacks.read permission.
 * @summary Get latest scan for stack
 */
export const getGetApiV1ServersServeridStacksStacknameVulnscanUrl = (serverid: number,
    stackname: string,) => {




  return `/api/v1/servers/${serverid}/stacks/${stackname}/vulnscan`
}

export const getApiV1ServersServeridStacksStacknameVulnscan = async (serverid: number,
    stackname: string, options?: RequestInit): Promise<GetLatestScanResponse> => {

  return apiClient<GetLatestScanResponse>(getGetApiV1ServersServeridStacksStacknameVulnscanUrl(serverid,stackname),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1ServersServeridStacksStacknameVulnscanQueryKey = (serverid: number,
    stackname: string,) => {
    return [
    `/api/v1/servers/${serverid}/stacks/${stackname}/vulnscan`
    ] as const;
    }


export const getGetApiV1ServersServeridStacksStacknameVulnscanQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscan>>, TError = ErrorResponse | void>(serverid: number,
    stackname: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscan>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ServersServeridStacksStacknameVulnscanQueryKey(serverid,stackname);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscan>>> = ({ signal }) => getApiV1ServersServeridStacksStacknameVulnscan(serverid,stackname, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(serverid && stackname), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscan>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ServersServeridStacksStacknameVulnscanQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscan>>>
export type GetApiV1ServersServeridStacksStacknameVulnscanQueryError = ErrorResponse | void


export function useGetApiV1ServersServeridStacksStacknameVulnscan<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscan>>, TError = ErrorResponse | void>(
 serverid: number,
    stackname: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscan>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscan>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscan>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ServersServeridStacksStacknameVulnscan<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscan>>, TError = ErrorResponse | void>(
 serverid: number,
    stackname: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscan>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscan>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscan>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ServersServeridStacksStacknameVulnscan<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscan>>, TError = ErrorResponse | void>(
 serverid: number,
    stackname: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscan>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get latest scan for stack
 */

export function useGetApiV1ServersServeridStacksStacknameVulnscan<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscan>>, TError = ErrorResponse | void>(
 serverid: number,
    stackname: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscan>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ServersServeridStacksStacknameVulnscanQueryOptions(serverid,stackname,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Starts a vulnerability scan for a stack. Requires stacks.read permission.
 * @summary Start vulnerability scan
 */
export const getPostApiV1ServersServeridStacksStacknameVulnscanUrl = (serverid: number,
    stackname: string,) => {




  return `/api/v1/servers/${serverid}/stacks/${stackname}/vulnscan`
}

export const postApiV1ServersServeridStacksStacknameVulnscan = async (serverid: number,
    stackname: string,
    startScanRequest: StartScanRequest, options?: RequestInit): Promise<StartScanResponse> => {

  return apiClient<StartScanResponse>(getPostApiV1ServersServeridStacksStacknameVulnscanUrl(serverid,stackname),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      startScanRequest,)
  }
);}




export const getPostApiV1ServersServeridStacksStacknameVulnscanMutationOptions = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ServersServeridStacksStacknameVulnscan>>, TError,{serverid: number;stackname: string;data: StartScanRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1ServersServeridStacksStacknameVulnscan>>, TError,{serverid: number;stackname: string;data: StartScanRequest}, TContext> => {

const mutationKey = ['postApiV1ServersServeridStacksStacknameVulnscan'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1ServersServeridStacksStacknameVulnscan>>, {serverid: number;stackname: string;data: StartScanRequest}> = (props) => {
          const {serverid,stackname,data} = props ?? {};

          return  postApiV1ServersServeridStacksStacknameVulnscan(serverid,stackname,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1ServersServeridStacksStacknameVulnscanMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1ServersServeridStacksStacknameVulnscan>>>
    export type PostApiV1ServersServeridStacksStacknameVulnscanMutationBody = StartScanRequest
    export type PostApiV1ServersServeridStacksStacknameVulnscanMutationError = ErrorResponse | void

    /**
 * @summary Start vulnerability scan
 */
export const usePostApiV1ServersServeridStacksStacknameVulnscan = <TError = ErrorResponse | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ServersServeridStacksStacknameVulnscan>>, TError,{serverid: number;stackname: string;data: StartScanRequest}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1ServersServeridStacksStacknameVulnscan>>,
        TError,
        {serverid: number;stackname: string;data: StartScanRequest},
        TContext
      > => {
      return useMutation(getPostApiV1ServersServeridStacksStacknameVulnscanMutationOptions(options), queryClient);
    }
    /**
 * Returns all vulnerability scans for a stack with summaries. Requires stacks.read permission.
 * @summary Get scan history for stack
 */
export const getGetApiV1ServersServeridStacksStacknameVulnscanHistoryUrl = (serverid: number,
    stackname: string,) => {




  return `/api/v1/servers/${serverid}/stacks/${stackname}/vulnscan/history`
}

export const getApiV1ServersServeridStacksStacknameVulnscanHistory = async (serverid: number,
    stackname: string, options?: RequestInit): Promise<GetScansHistoryResponse> => {

  return apiClient<GetScansHistoryResponse>(getGetApiV1ServersServeridStacksStacknameVulnscanHistoryUrl(serverid,stackname),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1ServersServeridStacksStacknameVulnscanHistoryQueryKey = (serverid: number,
    stackname: string,) => {
    return [
    `/api/v1/servers/${serverid}/stacks/${stackname}/vulnscan/history`
    ] as const;
    }


export const getGetApiV1ServersServeridStacksStacknameVulnscanHistoryQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanHistory>>, TError = ErrorResponse | void>(serverid: number,
    stackname: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanHistory>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ServersServeridStacksStacknameVulnscanHistoryQueryKey(serverid,stackname);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanHistory>>> = ({ signal }) => getApiV1ServersServeridStacksStacknameVulnscanHistory(serverid,stackname, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(serverid && stackname), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ServersServeridStacksStacknameVulnscanHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanHistory>>>
export type GetApiV1ServersServeridStacksStacknameVulnscanHistoryQueryError = ErrorResponse | void


export function useGetApiV1ServersServeridStacksStacknameVulnscanHistory<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanHistory>>, TError = ErrorResponse | void>(
 serverid: number,
    stackname: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanHistory>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ServersServeridStacksStacknameVulnscanHistory<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanHistory>>, TError = ErrorResponse | void>(
 serverid: number,
    stackname: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanHistory>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ServersServeridStacksStacknameVulnscanHistory<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanHistory>>, TError = ErrorResponse | void>(
 serverid: number,
    stackname: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanHistory>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get scan history for stack
 */

export function useGetApiV1ServersServeridStacksStacknameVulnscanHistory<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanHistory>>, TError = ErrorResponse | void>(
 serverid: number,
    stackname: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanHistory>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ServersServeridStacksStacknameVulnscanHistoryQueryOptions(serverid,stackname,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Returns vulnerability trend data for a stack. Requires stacks.read permission.
 * @summary Get scan trend for stack
 */
export const getGetApiV1ServersServeridStacksStacknameVulnscanTrendUrl = (serverid: number,
    stackname: string,
    params?: GetApiV1ServersServeridStacksStacknameVulnscanTrendParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/servers/${serverid}/stacks/${stackname}/vulnscan/trend?${stringifiedParams}` : `/api/v1/servers/${serverid}/stacks/${stackname}/vulnscan/trend`
}

export const getApiV1ServersServeridStacksStacknameVulnscanTrend = async (serverid: number,
    stackname: string,
    params?: GetApiV1ServersServeridStacksStacknameVulnscanTrendParams, options?: RequestInit): Promise<GetScanTrendResponse> => {

  return apiClient<GetScanTrendResponse>(getGetApiV1ServersServeridStacksStacknameVulnscanTrendUrl(serverid,stackname,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1ServersServeridStacksStacknameVulnscanTrendQueryKey = (serverid: number,
    stackname: string,
    params?: GetApiV1ServersServeridStacksStacknameVulnscanTrendParams,) => {
    return [
    `/api/v1/servers/${serverid}/stacks/${stackname}/vulnscan/trend`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1ServersServeridStacksStacknameVulnscanTrendQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanTrend>>, TError = ErrorResponse | void>(serverid: number,
    stackname: string,
    params?: GetApiV1ServersServeridStacksStacknameVulnscanTrendParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanTrend>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ServersServeridStacksStacknameVulnscanTrendQueryKey(serverid,stackname,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanTrend>>> = ({ signal }) => getApiV1ServersServeridStacksStacknameVulnscanTrend(serverid,stackname,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(serverid && stackname), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanTrend>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ServersServeridStacksStacknameVulnscanTrendQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanTrend>>>
export type GetApiV1ServersServeridStacksStacknameVulnscanTrendQueryError = ErrorResponse | void


export function useGetApiV1ServersServeridStacksStacknameVulnscanTrend<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanTrend>>, TError = ErrorResponse | void>(
 serverid: number,
    stackname: string,
    params: undefined |  GetApiV1ServersServeridStacksStacknameVulnscanTrendParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanTrend>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanTrend>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanTrend>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ServersServeridStacksStacknameVulnscanTrend<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanTrend>>, TError = ErrorResponse | void>(
 serverid: number,
    stackname: string,
    params?: GetApiV1ServersServeridStacksStacknameVulnscanTrendParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanTrend>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanTrend>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanTrend>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ServersServeridStacksStacknameVulnscanTrend<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanTrend>>, TError = ErrorResponse | void>(
 serverid: number,
    stackname: string,
    params?: GetApiV1ServersServeridStacksStacknameVulnscanTrendParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanTrend>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get scan trend for stack
 */

export function useGetApiV1ServersServeridStacksStacknameVulnscanTrend<TData = Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanTrend>>, TError = ErrorResponse | void>(
 serverid: number,
    stackname: string,
    params?: GetApiV1ServersServeridStacksStacknameVulnscanTrendParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ServersServeridStacksStacknameVulnscanTrend>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ServersServeridStacksStacknameVulnscanTrendQueryOptions(serverid,stackname,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Compares two vulnerability scans and returns new, fixed, and unchanged vulnerabilities. Both scans must be from the same stack. Requires stacks.read permission.
 * @summary Compare two scans
 */
export const getGetApiV1VulnscanCompareBaseScanIdCompareScanIdUrl = (baseScanId: number,
    compareScanId: number,) => {




  return `/api/v1/vulnscan/compare/${baseScanId}/${compareScanId}`
}

export const getApiV1VulnscanCompareBaseScanIdCompareScanId = async (baseScanId: number,
    compareScanId: number, options?: RequestInit): Promise<CompareScanResponse> => {

  return apiClient<CompareScanResponse>(getGetApiV1VulnscanCompareBaseScanIdCompareScanIdUrl(baseScanId,compareScanId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1VulnscanCompareBaseScanIdCompareScanIdQueryKey = (baseScanId: number,
    compareScanId: number,) => {
    return [
    `/api/v1/vulnscan/compare/${baseScanId}/${compareScanId}`
    ] as const;
    }


export const getGetApiV1VulnscanCompareBaseScanIdCompareScanIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1VulnscanCompareBaseScanIdCompareScanId>>, TError = ErrorResponse | void>(baseScanId: number,
    compareScanId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1VulnscanCompareBaseScanIdCompareScanId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1VulnscanCompareBaseScanIdCompareScanIdQueryKey(baseScanId,compareScanId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1VulnscanCompareBaseScanIdCompareScanId>>> = ({ signal }) => getApiV1VulnscanCompareBaseScanIdCompareScanId(baseScanId,compareScanId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(baseScanId && compareScanId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1VulnscanCompareBaseScanIdCompareScanId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1VulnscanCompareBaseScanIdCompareScanIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1VulnscanCompareBaseScanIdCompareScanId>>>
export type GetApiV1VulnscanCompareBaseScanIdCompareScanIdQueryError = ErrorResponse | void


export function useGetApiV1VulnscanCompareBaseScanIdCompareScanId<TData = Awaited<ReturnType<typeof getApiV1VulnscanCompareBaseScanIdCompareScanId>>, TError = ErrorResponse | void>(
 baseScanId: number,
    compareScanId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1VulnscanCompareBaseScanIdCompareScanId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1VulnscanCompareBaseScanIdCompareScanId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1VulnscanCompareBaseScanIdCompareScanId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1VulnscanCompareBaseScanIdCompareScanId<TData = Awaited<ReturnType<typeof getApiV1VulnscanCompareBaseScanIdCompareScanId>>, TError = ErrorResponse | void>(
 baseScanId: number,
    compareScanId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1VulnscanCompareBaseScanIdCompareScanId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1VulnscanCompareBaseScanIdCompareScanId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1VulnscanCompareBaseScanIdCompareScanId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1VulnscanCompareBaseScanIdCompareScanId<TData = Awaited<ReturnType<typeof getApiV1VulnscanCompareBaseScanIdCompareScanId>>, TError = ErrorResponse | void>(
 baseScanId: number,
    compareScanId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1VulnscanCompareBaseScanIdCompareScanId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Compare two scans
 */

export function useGetApiV1VulnscanCompareBaseScanIdCompareScanId<TData = Awaited<ReturnType<typeof getApiV1VulnscanCompareBaseScanIdCompareScanId>>, TError = ErrorResponse | void>(
 baseScanId: number,
    compareScanId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1VulnscanCompareBaseScanIdCompareScanId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1VulnscanCompareBaseScanIdCompareScanIdQueryOptions(baseScanId,compareScanId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Returns a specific vulnerability scan with all vulnerabilities. Requires stacks.read permission for the scanned stack.
 * @summary Get scan by ID
 */
export const getGetApiV1VulnscanScanidUrl = (scanid: number,) => {




  return `/api/v1/vulnscan/${scanid}`
}

export const getApiV1VulnscanScanid = async (scanid: number, options?: RequestInit): Promise<GetScanResponse> => {

  return apiClient<GetScanResponse>(getGetApiV1VulnscanScanidUrl(scanid),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1VulnscanScanidQueryKey = (scanid: number,) => {
    return [
    `/api/v1/vulnscan/${scanid}`
    ] as const;
    }


export const getGetApiV1VulnscanScanidQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1VulnscanScanid>>, TError = ErrorResponse | void>(scanid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1VulnscanScanid>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1VulnscanScanidQueryKey(scanid);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1VulnscanScanid>>> = ({ signal }) => getApiV1VulnscanScanid(scanid, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(scanid), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1VulnscanScanid>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1VulnscanScanidQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1VulnscanScanid>>>
export type GetApiV1VulnscanScanidQueryError = ErrorResponse | void


export function useGetApiV1VulnscanScanid<TData = Awaited<ReturnType<typeof getApiV1VulnscanScanid>>, TError = ErrorResponse | void>(
 scanid: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1VulnscanScanid>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1VulnscanScanid>>,
          TError,
          Awaited<ReturnType<typeof getApiV1VulnscanScanid>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1VulnscanScanid<TData = Awaited<ReturnType<typeof getApiV1VulnscanScanid>>, TError = ErrorResponse | void>(
 scanid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1VulnscanScanid>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1VulnscanScanid>>,
          TError,
          Awaited<ReturnType<typeof getApiV1VulnscanScanid>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1VulnscanScanid<TData = Awaited<ReturnType<typeof getApiV1VulnscanScanid>>, TError = ErrorResponse | void>(
 scanid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1VulnscanScanid>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get scan by ID
 */

export function useGetApiV1VulnscanScanid<TData = Awaited<ReturnType<typeof getApiV1VulnscanScanid>>, TError = ErrorResponse | void>(
 scanid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1VulnscanScanid>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1VulnscanScanidQueryOptions(scanid,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Returns vulnerability counts by severity for a scan. Requires stacks.read permission for the scanned stack.
 * @summary Get scan summary
 */
export const getGetApiV1VulnscanScanidSummaryUrl = (scanid: number,) => {




  return `/api/v1/vulnscan/${scanid}/summary`
}

export const getApiV1VulnscanScanidSummary = async (scanid: number, options?: RequestInit): Promise<GetScanSummaryResponse> => {

  return apiClient<GetScanSummaryResponse>(getGetApiV1VulnscanScanidSummaryUrl(scanid),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1VulnscanScanidSummaryQueryKey = (scanid: number,) => {
    return [
    `/api/v1/vulnscan/${scanid}/summary`
    ] as const;
    }


export const getGetApiV1VulnscanScanidSummaryQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1VulnscanScanidSummary>>, TError = ErrorResponse | void>(scanid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1VulnscanScanidSummary>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1VulnscanScanidSummaryQueryKey(scanid);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1VulnscanScanidSummary>>> = ({ signal }) => getApiV1VulnscanScanidSummary(scanid, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(scanid), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1VulnscanScanidSummary>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1VulnscanScanidSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1VulnscanScanidSummary>>>
export type GetApiV1VulnscanScanidSummaryQueryError = ErrorResponse | void


export function useGetApiV1VulnscanScanidSummary<TData = Awaited<ReturnType<typeof getApiV1VulnscanScanidSummary>>, TError = ErrorResponse | void>(
 scanid: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1VulnscanScanidSummary>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1VulnscanScanidSummary>>,
          TError,
          Awaited<ReturnType<typeof getApiV1VulnscanScanidSummary>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1VulnscanScanidSummary<TData = Awaited<ReturnType<typeof getApiV1VulnscanScanidSummary>>, TError = ErrorResponse | void>(
 scanid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1VulnscanScanidSummary>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1VulnscanScanidSummary>>,
          TError,
          Awaited<ReturnType<typeof getApiV1VulnscanScanidSummary>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1VulnscanScanidSummary<TData = Awaited<ReturnType<typeof getApiV1VulnscanScanidSummary>>, TError = ErrorResponse | void>(
 scanid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1VulnscanScanidSummary>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get scan summary
 */

export function useGetApiV1VulnscanScanidSummary<TData = Awaited<ReturnType<typeof getApiV1VulnscanScanidSummary>>, TError = ErrorResponse | void>(
 scanid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1VulnscanScanidSummary>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1VulnscanScanidSummaryQueryOptions(scanid,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




