/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ContainerStatusEvent,
  ResponseEmpty,
  StackStatusEvent,
  StreamMessage
} from '../models';

import { apiClient } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Upgrades to a WebSocket and pushes container_status and stack_status events for the named stack. The URL is the subscription: the stream is one-directional and any client data frame closes the connection. Authenticate with an Authorization Bearer header or the Bearer WebSocket subprotocol.
 * @summary Per-stack status event stream (WebSocket)
 */
export const getGetWsApiServersServeridStacksStacknameEventsUrl = (serverid: number,
    stackname: string,) => {




  return `/ws/api/servers/${serverid}/stacks/${stackname}/events`
}

export const getWsApiServersServeridStacksStacknameEvents = async (serverid: number,
    stackname: string, options?: RequestInit): Promise<void> => {

  return apiClient<void>(getGetWsApiServersServeridStacksStacknameEventsUrl(serverid,stackname),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetWsApiServersServeridStacksStacknameEventsQueryKey = (serverid: number,
    stackname: string,) => {
    return [
    `/ws/api/servers/${serverid}/stacks/${stackname}/events`
    ] as const;
    }


export const getGetWsApiServersServeridStacksStacknameEventsQueryOptions = <TData = Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameEvents>>, TError = ContainerStatusEvent | StackStatusEvent | ResponseEmpty | void>(serverid: number,
    stackname: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameEvents>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWsApiServersServeridStacksStacknameEventsQueryKey(serverid,stackname);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameEvents>>> = ({ signal }) => getWsApiServersServeridStacksStacknameEvents(serverid,stackname, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(serverid && stackname), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameEvents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWsApiServersServeridStacksStacknameEventsQueryResult = NonNullable<Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameEvents>>>
export type GetWsApiServersServeridStacksStacknameEventsQueryError = ContainerStatusEvent | StackStatusEvent | ResponseEmpty | void


export function useGetWsApiServersServeridStacksStacknameEvents<TData = Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameEvents>>, TError = ContainerStatusEvent | StackStatusEvent | ResponseEmpty | void>(
 serverid: number,
    stackname: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameEvents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameEvents>>,
          TError,
          Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWsApiServersServeridStacksStacknameEvents<TData = Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameEvents>>, TError = ContainerStatusEvent | StackStatusEvent | ResponseEmpty | void>(
 serverid: number,
    stackname: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameEvents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameEvents>>,
          TError,
          Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWsApiServersServeridStacksStacknameEvents<TData = Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameEvents>>, TError = ContainerStatusEvent | StackStatusEvent | ResponseEmpty | void>(
 serverid: number,
    stackname: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameEvents>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Per-stack status event stream (WebSocket)
 */

export function useGetWsApiServersServeridStacksStacknameEvents<TData = Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameEvents>>, TError = ContainerStatusEvent | StackStatusEvent | ResponseEmpty | void>(
 serverid: number,
    stackname: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameEvents>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetWsApiServersServeridStacksStacknameEventsQueryOptions(serverid,stackname,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Upgrades to a WebSocket and pushes the named operation's output as StreamMessage frames (stdout, stderr, progress, complete, error). Requires the same permission that starting the operation required. The stream is one-directional and any client data frame closes the connection. Authenticate with an Authorization Bearer header or the Bearer WebSocket subprotocol.
 * @summary Operation output stream (WebSocket)
 */
export const getGetWsApiServersServeridStacksStacknameOperationsOperationIdUrl = (serverid: number,
    stackname: string,
    operationId: string,) => {




  return `/ws/api/servers/${serverid}/stacks/${stackname}/operations/${operationId}`
}

export const getWsApiServersServeridStacksStacknameOperationsOperationId = async (serverid: number,
    stackname: string,
    operationId: string, options?: RequestInit): Promise<void> => {

  return apiClient<void>(getGetWsApiServersServeridStacksStacknameOperationsOperationIdUrl(serverid,stackname,operationId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetWsApiServersServeridStacksStacknameOperationsOperationIdQueryKey = (serverid: number,
    stackname: string,
    operationId: string,) => {
    return [
    `/ws/api/servers/${serverid}/stacks/${stackname}/operations/${operationId}`
    ] as const;
    }


export const getGetWsApiServersServeridStacksStacknameOperationsOperationIdQueryOptions = <TData = Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameOperationsOperationId>>, TError = StreamMessage | ResponseEmpty | void>(serverid: number,
    stackname: string,
    operationId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameOperationsOperationId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWsApiServersServeridStacksStacknameOperationsOperationIdQueryKey(serverid,stackname,operationId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameOperationsOperationId>>> = ({ signal }) => getWsApiServersServeridStacksStacknameOperationsOperationId(serverid,stackname,operationId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(serverid && stackname && operationId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameOperationsOperationId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWsApiServersServeridStacksStacknameOperationsOperationIdQueryResult = NonNullable<Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameOperationsOperationId>>>
export type GetWsApiServersServeridStacksStacknameOperationsOperationIdQueryError = StreamMessage | ResponseEmpty | void


export function useGetWsApiServersServeridStacksStacknameOperationsOperationId<TData = Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameOperationsOperationId>>, TError = StreamMessage | ResponseEmpty | void>(
 serverid: number,
    stackname: string,
    operationId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameOperationsOperationId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameOperationsOperationId>>,
          TError,
          Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameOperationsOperationId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWsApiServersServeridStacksStacknameOperationsOperationId<TData = Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameOperationsOperationId>>, TError = StreamMessage | ResponseEmpty | void>(
 serverid: number,
    stackname: string,
    operationId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameOperationsOperationId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameOperationsOperationId>>,
          TError,
          Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameOperationsOperationId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWsApiServersServeridStacksStacknameOperationsOperationId<TData = Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameOperationsOperationId>>, TError = StreamMessage | ResponseEmpty | void>(
 serverid: number,
    stackname: string,
    operationId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameOperationsOperationId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Operation output stream (WebSocket)
 */

export function useGetWsApiServersServeridStacksStacknameOperationsOperationId<TData = Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameOperationsOperationId>>, TError = StreamMessage | ResponseEmpty | void>(
 serverid: number,
    stackname: string,
    operationId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWsApiServersServeridStacksStacknameOperationsOperationId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetWsApiServersServeridStacksStacknameOperationsOperationIdQueryOptions(serverid,stackname,operationId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




