/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */

export interface AddScopeRequest {
  permission: string;
  /**
   * @minimum 0
   * @nullable
   */
  server_id?: number | null;
  stack_pattern: string;
}
