/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */

export interface APIKeyResponse {
  created_at: string;
  /** @nullable */
  expires_at: string | null;
  /** @minimum 0 */
  id: number;
  is_active: boolean;
  key_prefix: string;
  /** @nullable */
  last_used_at: string | null;
  name: string;
  scope_count: number;
  updated_at: string;
}
