/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import type { BuildCacheInfo } from './buildCacheInfo';

export interface BuildCacheSummary {
  cache: BuildCacheInfo[];
  total_count: number;
  total_size: number;
}
