/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import type { BuildConfigArgs } from './buildConfigArgs';

export interface BuildConfig {
  args?: BuildConfigArgs;
  cache_from?: string[];
  cache_to?: string[];
  context?: string;
  dockerfile?: string;
  platforms?: string[];
  target?: string;
}
