/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import type { CanCreateStackData } from './canCreateStackData';

export interface CanCreateStackResponse {
  data: CanCreateStackData;
  success: boolean;
}
