/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import type { ComposeChangesAddServices } from './composeChangesAddServices';
import type { ComposeChangesConfigChanges } from './composeChangesConfigChanges';
import type { ComposeChangesNetworkChanges } from './composeChangesNetworkChanges';
import type { ComposeChangesRenameServices } from './composeChangesRenameServices';
import type { ComposeChangesSecretChanges } from './composeChangesSecretChanges';
import type { ComposeChangesServiceChanges } from './composeChangesServiceChanges';
import type { ComposeChangesVolumeChanges } from './composeChangesVolumeChanges';

export interface ComposeChanges {
  add_services?: ComposeChangesAddServices;
  config_changes?: ComposeChangesConfigChanges;
  delete_services?: string[];
  network_changes?: ComposeChangesNetworkChanges;
  rename_services?: ComposeChangesRenameServices;
  secret_changes?: ComposeChangesSecretChanges;
  service_changes?: ComposeChangesServiceChanges;
  volume_changes?: ComposeChangesVolumeChanges;
}
