/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import type { ContainerInfoLabels } from './containerInfoLabels';

export interface ContainerInfo {
  created: string;
  id: string;
  image: string;
  labels: ContainerInfoLabels;
  name: string;
  size: number;
  state: string;
  status: string;
}
