/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import type { ContainerInfo } from './containerInfo';

export interface ContainerSummary {
  containers: ContainerInfo[];
  running_count: number;
  stopped_count: number;
  total_count: number;
  total_size: number;
}
