/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import type { ImageHistoryLayer } from './imageHistoryLayer';
import type { ImageInspectInfo } from './imageInspectInfo';

export interface ContainerImageDetails {
  container_name: string;
  image_history: ImageHistoryLayer[];
  image_id: string;
  image_info: ImageInspectInfo;
  image_name: string;
}
