/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */

export interface ContainerNetwork {
  aliases?: string[];
  gateway?: string;
  ip_address?: string;
  mac_address?: string;
  name: string;
  network_id?: string;
}
