/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import type { APIKeyInfo } from './aPIKeyInfo';

export interface CreateAPIKeyResponseData {
  api_key: APIKeyInfo;
  message?: string;
  plain_key: string;
}
