/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import type { PlacementConfig } from './placementConfig';
import type { ResourcesConfig } from './resourcesConfig';
import type { RestartPolicyConfig } from './restartPolicyConfig';
import type { UpdateRollbackConfig } from './updateRollbackConfig';

export interface DeployConfig {
  /** @nullable */
  mode?: string | null;
  placement?: PlacementConfig | null;
  /** @nullable */
  replicas?: number | null;
  resources?: ResourcesConfig | null;
  restart_policy?: RestartPolicyConfig | null;
  rollback_config?: UpdateRollbackConfig | null;
  update_config?: UpdateRollbackConfig | null;
}
