/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */

export interface DiskUsage {
  build_cache_size: number;
  containers_size: number;
  images_size: number;
  layers_size: number;
  total_size: number;
  volumes_size: number;
}
