/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */

export interface EnvironmentVariable {
  is_from_container: boolean;
  is_sensitive: boolean;
  key: string;
  source: string;
  value: string;
}
