/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV1AdminPermissionsParams = {
/**
 * Filter type - use 'role' to exclude API-key-only permissions
 */
type?: string;
};
