/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV1AdminOperationLogsStatus = typeof GetApiV1AdminOperationLogsStatus[keyof typeof GetApiV1AdminOperationLogsStatus];


export const GetApiV1AdminOperationLogsStatus = {
  complete: 'complete',
  incomplete: 'incomplete',
  failed: 'failed',
  success: 'success',
} as const;
