/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV1AdminSecurityAuditLogsParams = {
/**
 * Page number
 * @minimum 1
 */
page?: number;
/**
 * Number of items per page
 * @minimum 1
 * @maximum 100
 */
per_page?: number;
/**
 * Filter by event type
 */
event_type?: string;
/**
 * Filter by event category
 */
event_category?: string;
/**
 * Filter by severity
 */
severity?: string;
/**
 * Filter by actor user ID
 */
actor_user_id?: string;
/**
 * Filter by success status (true/false)
 */
success?: string;
/**
 * Filter by start date (RFC3339 format)
 */
start_date?: string;
/**
 * Filter by end date (RFC3339 format)
 */
end_date?: string;
/**
 * Search in actor username, target name, or event type
 */
search?: string;
};
