/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV1ServersServeridStacksStacknameFilesDownloadParams = {
/**
 * File path to download
 */
path: string;
/**
 * Optional filename for the downloaded file
 */
filename?: string;
};
