/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV1ServersServeridStacksStacknameContainersContainerNameLogsParams = {
/**
 * Number of log lines to return
 */
tail?: number;
/**
 * Only return logs since this timestamp (RFC3339 format)
 */
since?: string;
/**
 * Include timestamps in log output
 */
timestamps?: boolean;
};
