/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import type { GetLatestScanData } from './getLatestScanData';

export interface GetLatestScanResponse {
  data: GetLatestScanData;
  success: boolean;
}
