/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import type { PerImageTrend } from './perImageTrend';
import type { ScanTrendPoint } from './scanTrendPoint';

export interface GetScanTrendData {
  per_image_trend: PerImageTrend[];
  scope_warning?: string;
  stack_trend: ScanTrendPoint[];
}
