/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import type { DeletedAt } from './deletedAt';
import type { ImageVulnerability } from './imageVulnerability';
import type { ScanScope } from './scanScope';

export interface ImageScan {
  agent_scan_id: string;
  /** @nullable */
  completed_at?: string | null;
  created_at: string;
  deleted_at?: DeletedAt;
  error_message?: string;
  /** @minimum 0 */
  id: number;
  last_poll_error?: string;
  /** @nullable */
  last_polled_at?: string | null;
  poll_failures: number;
  scanned_images: number;
  scopes?: ScanScope[];
  /** @minimum 0 */
  server_id: number;
  service_filter?: string;
  stack_name: string;
  started_at: string;
  status: string;
  total_images: number;
  updated_at: string;
  vulnerabilities?: ImageVulnerability[];
}
