/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import type { ImageConfig } from './imageConfig';
import type { RootFS } from './rootFS';

export interface ImageInspectInfo {
  architecture: string;
  author: string;
  config: ImageConfig;
  created: string;
  docker_version: string;
  os: string;
  parent?: string;
  repo_digests?: string[];
  repo_tags?: string[];
  rootfs: RootFS;
  size: number;
  virtual_size: number;
}
