/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import type { ImageConfigExposedPorts } from './imageConfigExposedPorts';
import type { ImageConfigLabels } from './imageConfigLabels';

export interface ImageConfig {
  cmd?: string[];
  entrypoint?: string[];
  env?: string[];
  exposed_ports?: ImageConfigExposedPorts;
  labels?: ImageConfigLabels;
  user?: string;
  working_dir?: string;
}
