/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */

export interface ImportSummary {
  permissions_imported: number;
  roles_imported: number;
  servers_imported: number;
  totp_secrets_imported: number;
  users_imported: number;
}
