/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import type { ListStacksData } from './listStacksData';

export interface ListStacksResponse {
  data: ListStacksData;
  success: boolean;
}
