/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import type { PermissionInfo } from './permissionInfo';
import type { RoleInfo } from './roleInfo';
import type { ServerInfo2 } from './serverInfo2';
import type { StackPermissionRule } from './stackPermissionRule';

export interface ListRoleStackPermissionsData {
  permissionRules: StackPermissionRule[];
  permissions: PermissionInfo[];
  role: RoleInfo;
  servers: ServerInfo2[];
}
