/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import type { BuildCacheSummary } from './buildCacheSummary';
import type { ContainerSummary } from './containerSummary';
import type { DiskUsage } from './diskUsage';
import type { ImageSummary } from './imageSummary';
import type { NetworkSummary } from './networkSummary';
import type { SystemInfo } from './systemInfo';
import type { VolumeSummary } from './volumeSummary';

export interface MaintenanceInfo {
  build_cache_summary: BuildCacheSummary;
  container_summary: ContainerSummary;
  disk_usage: DiskUsage;
  image_summary: ImageSummary;
  last_updated: string;
  network_summary: NetworkSummary;
  system_info: SystemInfo;
  volume_summary: VolumeSummary;
}
