/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import type { IpamConfig } from './ipamConfig';
import type { NetworkConfigDriverOpts } from './networkConfigDriverOpts';
import type { NetworkConfigLabels } from './networkConfigLabels';

export interface NetworkConfig {
  driver?: string;
  driver_opts?: NetworkConfigDriverOpts;
  external?: boolean;
  ipam?: IpamConfig | null;
  labels?: NetworkConfigLabels;
  name?: string;
}
