/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */

export interface NetworkEndpoint {
  endpoint_id?: string;
  ipv4_address?: string;
  ipv6_address?: string;
  mac_address?: string;
  name: string;
}
