/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import type { NetworkInfo } from './networkInfo';

export interface NetworkSummary {
  networks: NetworkInfo[];
  total_count: number;
  unused_count: number;
}
