/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import type { NewServiceConfigEnvironment } from './newServiceConfigEnvironment';
import type { PortMapping } from './portMapping';
import type { VolumeMount2 } from './volumeMount2';

export interface NewServiceConfig {
  environment?: NewServiceConfigEnvironment;
  image: string;
  ports?: PortMapping[];
  restart?: string;
  volumes?: VolumeMount2[];
}
