/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import type { DeletedAt } from './deletedAt';
import type { OperationLog } from './operationLog';

export interface OperationLogMessage {
  created_at: string;
  deleted_at: DeletedAt;
  /** @minimum 0 */
  id: number;
  message_data: string;
  message_type: string;
  operation_log: OperationLog;
  /** @minimum 0 */
  operation_log_id: number;
  sequence_number: number;
  timestamp: string;
  updated_at: string;
}
