/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */

export interface PermissionInfo {
  action: string;
  description: string;
  /** @minimum 0 */
  id: number;
  is_api_key_only: boolean;
  name: string;
  resource: string;
}
