/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteCredentialMessageData } from './deleteCredentialMessageData';
import type { Error } from './error';
import type { Meta } from './meta';

export interface ResponseDeleteCredentialMessageData {
  data: DeleteCredentialMessageData;
  error?: Error | null;
  meta?: Meta | null;
  success: boolean;
}
