/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import type { VulnerabilitySummary } from './vulnerabilitySummary';

export interface ScanTrendPoint {
  date: string;
  /** @minimum 0 */
  scan_id: number;
  summary: VulnerabilitySummary | null;
}
