/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import type { DeletedAt } from './deletedAt';

export interface ScanScope {
  created_at: string;
  deleted_at: DeletedAt;
  /** @minimum 0 */
  id: number;
  image_name: string;
  /** @minimum 0 */
  scan_id: number;
  updated_at: string;
}
