/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import type { DeletedAt } from './deletedAt';

export interface Server {
  created_at: string;
  deleted_at?: DeletedAt;
  description: string;
  host: string;
  /** @minimum 0 */
  id: number;
  is_active: boolean;
  name: string;
  port: number;
  /** @nullable */
  skip_ssl_verification?: boolean | null;
  updated_at: string;
}
