/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import type { BuildConfig } from './buildConfig';
import type { CommandConfig } from './commandConfig';
import type { DeployConfig } from './deployConfig';
import type { HealthcheckConfig } from './healthcheckConfig';
import type { PortMapping } from './portMapping';
import type { ServiceChangesDependsOn } from './serviceChangesDependsOn';
import type { ServiceChangesEnvironment } from './serviceChangesEnvironment';
import type { ServiceChangesLabels } from './serviceChangesLabels';
import type { ServiceChangesNetworks } from './serviceChangesNetworks';
import type { VolumeMount2 } from './volumeMount2';

export interface ServiceChanges {
  build?: BuildConfig | null;
  command?: CommandConfig | null;
  depends_on?: ServiceChangesDependsOn;
  deploy?: DeployConfig | null;
  entrypoint?: CommandConfig | null;
  environment?: ServiceChangesEnvironment;
  healthcheck?: HealthcheckConfig | null;
  /** @nullable */
  image?: string | null;
  labels?: ServiceChangesLabels;
  networks?: ServiceChangesNetworks;
  /** @nullable */
  ports?: PortMapping[] | null;
  /** @nullable */
  restart?: string | null;
  /** @nullable */
  volumes?: VolumeMount2[] | null;
}
