/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */

export interface ServerUpdateRequest {
  access_token: string;
  description: string;
  host: string;
  is_active: boolean;
  name: string;
  port: number;
  /** @nullable */
  skip_ssl_verification: boolean | null;
}
