/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */

export interface StackPermissionRule {
  /** @minimum 0 */
  id: number;
  is_stack_based: boolean;
  /** @minimum 0 */
  permission_id: number;
  /** @minimum 0 */
  server_id: number;
  stack_pattern: string;
}
