/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import type { ComposeService } from './composeService';

export interface StackDetails {
  compose_file: string;
  name: string;
  path: string;
  /** @minimum 0 */
  server_id: number;
  server_name: string;
  services: ComposeService[];
}
