/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */

export interface SystemInfo {
  api_version: string;
  architecture: string;
  docker_root_dir: string;
  kernel_version: string;
  ncpu: number;
  os: string;
  server_version: string;
  storage_driver: string;
  total_memory: number;
  version: string;
}
