/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateRollbackConfig {
  delay?: string;
  failure_action?: string;
  max_failure_ratio?: number;
  monitor?: string;
  order?: string;
  /** @nullable */
  parallelism?: number | null;
}
