/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */
import type { DeletedAt } from './deletedAt';
import type { Role } from './role';

export interface User {
  created_at: string;
  deleted_at: DeletedAt;
  email: string;
  /** @nullable */
  email_verified_at: string | null;
  /** @minimum 0 */
  id: number;
  /** @nullable */
  last_login_at: string | null;
  roles: Role[];
  updated_at: string;
  username: string;
}
