/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Berth API
 * Berth: Opinionated docker compose stack management API
 * OpenAPI spec version: 1.0.0
 */

export interface WriteFileRequest {
  content: string;
  encoding?: string;
  /**
     * @minimum 0
     * @nullable
     */
  group_id?: number | null;
  /** @nullable */
  mode?: string | null;
  /**
     * @minimum 0
     * @nullable
     */
  owner_id?: number | null;
  path: string;
}
